### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#106]
Setup Authentication with SciDuct for the net.science web app.

1.  Perform authentication, storing authentication in session storage
2. Add timer to watch for idle status and logout when the user has been idle for a configurable amount of time.
3. Periodically check the token for expiration.  If user is not idle and there is more than less than 25% of the time left until the token expires, refresh the token.
4. Store the decoded token in session storage.
5. Add the "user" icon to the header for logging in/out

**Comment by Annapurna-Kupast** [comment]
@dmachi 
Hi Dustin,

User Service of SciDuct is integrated with Net.Science.
The requirements mentioned in the issue are implemented. Could you please verify and close the ticket.

Regards,
Annapurna.

**Comment by Annapurna-Kupast** [comment]
User Service of SciDuct is integrated with Net.Science. Closing the ticket
