### ISSUE TITLE
FileService Explorer

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#107]
Implement FileService explorer like functionality.  Begin with the Fuse-React explorer.

1.  Should work for both authenticated users and non-authenticated users (the latter for publicly visible files only
2. Define a strategy for creating type-specific viewers of files in the browser.  CSV/TSV, JSON, Images, PDFs, vega visualizations

**Comment by Annapurna-Kupast** [comment]
@dmachi 
Hi Dustin,

File Service of SciDuct is integrated with Net.Science.
The requirements mentioned in the issue are implemented. Could you please verify and close the ticket.

Regards,
Annapurna.

**Comment by Annapurna-Kupast** [comment]
File Service of SciDuct is integrated with Net.Science.
Closing the ticket
