### ISSUE TITLE
SNAP structural anlaysis code.  Running codes for auto-generating driver codes

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#110]
This has taken me a long time to get to.  I apologize.

I cannot run the codes.

The repo is here:  https://github.com/NSSAC/cines-parsing-snap

I have cloned the repo on rivanna.

I am trying to run on rivanna.

I go to the parsing directory (cines-parsing-snap/parsing-01/test).  I changed the run.?? and run.1?? scripts to be executable:
chmod u+x run.??
chmod u+x run.1??
(I checked these files into github.)

I then executed "./run.all" and it appears to build all intermediate representations (IRs).

Then, drilling down to:
cines-parsing-snap/constructing-drivers-01/test

I copy over the IRs from the parsing code.
I use run.copy.output.from.parser.
I first change the srcDir inside this file so it is a relative path so that it works from any directory on any system.
I check it into github.
I run ./run.copy.output.from.parser
It appears to copy over all IRs from the "parsing-code" 

Now,  I want to build all driver code main() methods.
I execute run.all:   ./run.all
This code appears to have only the original 30 codes.  It has none of the methods that you guys did.
**Do you have a run.all file that needs to be checked in to github?  (Just guessing).**

Thanks.
Again, sorry for my lateness.

@Lucaslhm 

chris

**Comment by cckuhlman** [comment]
The file run.diff.all also appears to be behind.  That is, like run.all, it only has the first 30 codes.  These are the ones we delivered to you.  I expected both to have all of the codes in them.  In other words, I expected them to look something like cines-parsing-snap/parsing-01/test/run.all, where all of the codes are represented.

There may be other scripts besides run.all and run.diff.all, but I think that these are the major ones.

Thanks.

**Comment by anju-thute** [comment]
Hey Chris,

Yes correct, we missed out to commit run.all file and run.diff.all. We will let you know once we commit all this file into the GitHub.

Thanks,
Anju

**Comment by cckuhlman** [comment]
Thanks Anju.  And sorry for making this delay so long, making things more difficult for you all.  chris
________________________________

**Comment by anju-thute** [comment]
Hey Chris,
 
Files have been committed in GitHub. We have updated run.all file along with run.diff.all and also created run.diff.xx files. 
 
In run.all file there is a variable **infilenos** in which we have assigned numbers of all the input files that would be executed in sequence. Since we had skipped some files previously due to inappropriate input files or method overloading, there is no driver code for some of the files. But we have added their sequence number in the run.all file.  While running run.all file there might be file not found exception which may occur for such files, but it wont effect the overall execution.
 
We can update that file if required by removing the  number from **infilenos** for such files, so that it would execute without any exception.
 
Thanks,
Anju

**Comment by cckuhlman** [comment]
Hey Anju:

Below are some more issues.

One thing you might consider is just make sure that you have committed your changes to github----we may not be using the latest codes in some cases.  I say this because there are a handful of cases where the summary table here (https://github.com/NSSAC/cines-snap-texts/blob/master/methods-to-implement/library-methods-to-implement.md) where you have written that verification is done, but we cannot build the main() method driver code, or there is some other issue that prevents us from confirming the verification.  So it seems like a fundamental disconnect.

code 40, method ConvertESubGraph(), does not run, but the summary file says it runs and is validated.  At least I could not get it to run.  The main method driver code is different from the *.py.valid code.

code 42, method ConvertSubGraph(), does not run, but the summary file says it runs and is validated.  At least I could not get it to run. The main method driver code is different from the *.py.valid code.

code 53 runs, but there is no *.py.valid driver code.

code 77, method GetESubGraph(), has different *.py and *.py.valid files.

code 78, method GetEdgesInOut(), seems to have a bad template.  On line 245, there is the line:  idx += 1.  This appears to be outside of the loop, but it seems like it needs to go inside the loop (i.e., needs to be indented).  I think this is in a template.  If so, please see what template it is, correct the template, and look at all other methods that use this template and correct them.

In the parsing code directory, every run.diff.XX, where XX is a number like 43, the code inside those files is **not** diffing files, but rather **copying** files.  This is a bit disconcerting.  I do not know how this happened, but copying newly generated files to the valid file counterpart is very different from diffing two files, and it can be a big problem.  It is a huge problem.  Maybe I did this, or maybe UVA did this, but it is pretty disturbing that this could happen.  We all need to be more careful.

code 104, method GetNodesAtHops(), I do not know how this was validated.  The diffing operations are specified with respect to files that are not even produced by this code.  I have corrected this.


code 44, method DelNodes(), is wrong.  The root cause is that the method signature type, input, is wrong.  The text file describing the method should have the single argument (a name of a graph) as *inout* and not *input*.  **I will deal with this problem.** Just letting you know. 

code 66.  This code is discussed in issue #75.  But I guess we gave up on this because the method has a "1" in the name.

code 114.  The method GetSubGraphRenumber().  The listing here (https://github.com/NSSAC/cines-snap-texts/blob/master/methods-to-implement/library-methods-to-implement.md) says it runs.  But the driver code main() method does not build for me, so I cannot test it.

code 130.  Method DrawGViz().  There is no valid driver main() method file:  *.py.valid.

code 134.  The method PlotEigValRank().  The code does not run.  There is an extra apostrophe in the comment for variable NumEigenvalues in the argparse method.  The apostrophe on eigenvalues' does not appear to be necessary and am not sure where it is coming in.  The original text file infile134.inp does not appear to have this apostrophe.

code 84 had an error.  The snap text file was missing an "s" on the end of the method name.  I fixed this, verified, and pushed to git.

******
PLEASE, PLEASE DO **NOT** MAKE WHOLESALE COMMITS TO THE GITHUB REPO.
Rather, only make surgical commits to github.  We have spent a lot of time going over the methods and the validation cases, and we do not want to have to do this again.
*******

Finally, I write this just so people know.  I should have gotten on this a month ago (possibly more by now).  I am sorry, I had other deadlines and could not get to it.  So if you need time to get geared back up on this, that is fine with me and understandable.

chris

**Comment by murli1201** [comment]
Hi Chris,

We had a look at all the issues and made the necessary changes for most of them and have committed only the fixes done to GitHub. Here are the details:

•	code 40 & code 77 - We had created a new datatype 'TIntSubgraph' for these snap methods. One of them had a parameter 'Graph' and the other had parameter 'InGraph' which caused some issues. I have changed all the traces of 'Graph' to 'InGraph' for both the codes as well as the datatype. The *.py and *.py.valid files are now same for both the codes.
•	code 42 -  Discussed the issue in detail in Tuesday's meeting. Chris to look at it, hence no changes are committed
•	code 53 - *.py.valid driver code was committed earlier. Could you please check it again?
•	code 78 - I have indented idx += 1 in the template and made changes to the driver codes for all the methods that use this template. I have generated the outputs again with the updated code.
•	code 114 - There was an extra hyphen(-) in the infile114 which caused this issue. I removed it and committed the updated files and driver code.
•	code 130 - I missed this. I have committed the *.py.valid file.
•	code 134 - I have removed the extra apostrophe from all the files and have committed the updated files for this one.
Apart from these issues, I have changed all the run.diff.* files in the parsing directory. They all had the logic of copying which is now changed to the logic of diffing two files.

**Comment by cckuhlman** [comment]
I have updated all files (Snap text input, IRs, driver code) and I have checked the verification/validation cases (I had to update the run.all script because it was not working on my mac).  All files for this are checked into github, so this code 42 is now done.   Thanks.

**Comment by cckuhlman** [comment]
I have checked the code 53, GenGrid().  It is fine now.  Went through all steps.  Modified a couple of run.* scripts for this method and checked into github.
