### ISSUE TITLE
File upload feature to be implemented for Net.Science

### ISSUE THREAD

**Issue by Annapurna-Kupast** [NSSAC/CINES#111]
File upload feature to be implemented for Net.Science:

- Ability to upload multiple files in a single go

- User should be able to choose a file, edit the File Type prior to uploading to File Manager

- Good to have - drag and drop facility to upload multiple file

- The users belonging to a team with WriteACL or ReadACL permissions should be allowed to upload a file to File manager

**Comment by dmachi** [comment]
Note: Users must have writeACL privileges (either by user or by team) for the folder they want to upload to.
