### ISSUE TITLE
Download file feature to be implemented for Net.Science

### ISSUE THREAD

**Issue by Annapurna-Kupast** [NSSAC/CINES#112]
Download file feature to be implemented for Net.Science

- The user belonging to a team with WriteACL, ReadACL or if user has been given WriteACL or ReadACL permission, such user(s) should be able to download the files

**Comment by dmachi** [comment]
Note: Independent of team membership, the requesting user can download a file if they are the owner of that file or if they themselves have been granted read or write privy.

**Comment by murli1201** [comment]
@dmachi 

Hi Dustin,

The QA testing cycle for the download functionality is completed and all the changes are committed into the repository and a tag : 'https://github.com/NSSAC/CINES/tree/CINES_Changes_Before_Drag_Drop_Feature_For_Upload' is created which consists of the changes.
