### ISSUE TITLE
Delete feature to be implemented for Net.Science

### ISSUE THREAD

**Issue by Annapurna-Kupast** [NSSAC/CINES#113]
Delete feature to be implemented for Net.Science

- Owners of a file should be allowed to delete the file.

@dmachi to confirm if users or teams with WriteACL should be allowed to delete a file

**Comment by Annapurna-Kupast** [comment]
Dustin confirmed in one of the calls - only the owner should be allowed to delete a file.

**Comment by murli1201** [comment]
@dmachi 

Hi Dustin,

The QA testing cycle for the delete functionality is completed and all the changes are committed into the repository and a tag : 'https://github.com/NSSAC/CINES/tree/CINES_Changes_Before_Drag_Drop_Feature_For_Upload' is created which consists of the changes.
