### ISSUE TITLE
new  package required for the python virtual environment in which the SNAP methods run, for plots

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#116]
Persistent stated that they had to update the python virtual environment, in which the SNAP driver codes run, to deal with the SNAP codes that generate plots as output.  The methods are listed in the method summary file in github at:
https://github.com/NSSAC/cines-snap-texts/blob/master/methods-to-implement/library-methods-to-implement.md
The methods are under the heading "Secondary priorities."
This new package will be put into that file, so that we know that this package is needed for these plotting methods.
This will also be required by Lucas, because he is generating the singularity image in which all of these methods will run, and this image will be in sciduct (and net.science).  This image will require this new package.

**Comment by murli1201** [comment]
Hi Chris,

I have added the the names of packages along with the methods that would require them in the method summary file in github at: https://github.com/NSSAC/cines-snap-texts/blob/master/methods-to-implement/library-methods-to-implement.md
