### ISSUE TITLE
update the SNAP method summary markdown file with changes that they had to make in the overall build and verification process

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#117]
Persistent went through several SNAP methods today that required some (small) changes.  These are listed in issue 110 in github, at:
https://github.com/NSSAC/CINES/issues/110

We ask Persistent to please update the method summary markdown file at:
https://github.com/NSSAC/cines-snap-texts/blob/master/methods-to-implement/library-methods-to-implement.md
with all of the changes needed for the methods demoed today for us, since we need to know these changes for future builds of these codes, e.g., for future versions of SNAP.

**Comment by murli1201** [comment]
Hi Chris,

I have updated the methods discussed in git issue 110 as per required in the method summary file in github at: https://github.com/NSSAC/cines-snap-texts/blob/master/methods-to-implement/library-methods-to-implement.md
