### ISSUE TITLE
Ability to edit meta data of a file or folder to be implemented for Net.Science

### ISSUE THREAD

**Issue by Annapurna-Kupast** [NSSAC/CINES#118]
Ability to edit meta data of a file or folder to be implemented for Net.Science
 
- The user belonging to a team with WriteACL or if user has been granted WriteACL permission, such user(s) should be able to edit the metadata of a file or folder.
- Dustin also mentioned, he would want the ability for the user to edit meta data with minimum clicks

**Comment by murli1201** [comment]
Implemented
