### ISSUE TITLE
Job Queue Monitoring

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#119]
Implement Job Queue monitor for Net.Science.  It should allow:

1. Refreshing
2. Filtering based on Job state and Type

**Comment by hcars** [comment]
@dmachi, the filtering feature appears to have a problem when filtering by state. When I click the filter button, select to filter by status, and select a status, I cannot click the apply filter button.

**Comment by dmachi** [comment]
Did you click the “add” button before trying to click apply?  I think it is kind of confusing, but that’s how they have it implemented currently.  We’ll probably adjust that in the next release.

**Comment by hcars** [comment]
Ah ok it is working as intended.
