### ISSUE TITLE
requests for changes/updates to the "publications" page of net.science (https://net.science)

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#121]
Several changes here:

1. Make bold the following headings:
-Links to Educational Materials on Network Science:   (delete the colon)
-Publications Acknowledging Support from CINES NSF Grant OAC-1916805:   (delete the colon)
-Publications Related to CINES:  (delete the colon)

2.  Put some vertical space (of about 1/4 of an inch) before the second and third headings above.  This is to separate out the three groupings.

3.  Change this item:
-G. Korkmaz, C. J. Kuhlman, S. S. Ravi and F. Vega-Redondo, “An Agent-Based Model of Common Knowledge and Collective Action Dynamics on Social Networks,” submitted for publication.

to this

-C. J. Kuhlman, G. Korkmaz, S. S. Ravi and F. Vega-Redondo, “An Agent-Based Model of Common Knowledge and Collective Action Dynamics on Social Networks,” Winter Simulation Conference (WSC), 2020.

4. Under heading:  Publications Acknowledging Support from CINES NSF Grant OAC-1916805:
-for each bulleted item, delete any occurrences of "to appear in" so that it just lists the conference or journal without this 3-word phrase.

5.  Under heading:  Publications Related to CINES
-make two subheadings:
    - works on cyberinfrastructure
    - works on applications
-take the first two papers currently under this main heading and put them under the first subheading.
-take the 3rd and 4th papers currently under this main heading and put them under the second subheading.

6.  Now adding new papers.  These papers will be added under the two subheadings just made in step number 5 above.
- Add this paper to be the ***first*** paper under the subheading "works on cyberinfrastructure"

Nesreen K. Ahmed, Richard A. Alo, Catherine T. Amelink, Young Yun Baek, Aashish Chaudhary, Kristy Collins, Albert C.  Esterline, Edward A. Fox, Geoffrey C. Fox, Aric Hagberg, Ron Kenyon, Chris J. Kuhlman, Jure Leskovec, Dustin Machi, Madhav V. Marathe, Natarajan Meghanathan, Yasuo Miyazaki, Judy Qiu, Naren Ramakrishnan, S. S. Ravi, Ryan A. Rossi, Rok Sosic, Gregor von Laszewski, “net.science:  A Cyberinfrastructure for Sustained Innovation in Network Science and Engineering,” Gateways Conference, 2020.

- Add all of these papers under the ***second*** heading "works on applications," after the two papers that will be there.

Joshua D. Priest, Madhav V. Marathe, S. S. Ravi, Daniel J. Rosenkrantz and Richard E. Stearns, “Evolution of Similar Configurations in Graph Dynamical Systems”, The 9th International Conference on Complex Networks and their Applications  (ComplexNetworks), 2020.

Rosemary Kim, Jagdish Gangolly, S. S. Ravi and Daniel J. Rosenkrantz, “Formal Analysis of Segregation of Duties (SoD) in Accounting:  A Computational Approach”, Abacus (A WileyJournal of Accounting, Finance and Business Studies), Vol.  56, No.  2, June 2020, pp. 165–212.

Abhijin  Adiga, Chris J. Kuhlman, Madhav V. Marathe, S. S. Ravi, Daniel J. Rosenkrantz, Richard E. Stearns and Anil K. Vullikanti,  “Bounds and Complexity Results for Learning Coalition-Based Interaction Functions in Networked Social Systems,” Proc.  32nd AAAI Conference on Artificial Intelligence (AAAI-2020), New York, NY, Feb. 2020, pp. 3138–3145.

Henry L. Carscadden, Chris J. Kuhlman, Madhav V. Marathe, S. S. Ravi, and Daniel J. Rosenkrantz, “Blocking the Propagation of Two Simultaneous Contagions over Networks,” The 9th International Conference on Complex Networks and their Applications (Complex Networks), 2020.

Chris J. Kuhlman, Gizem Korkmaz, S. S. Ravi, and Fernando Vega-Redondo, “Effect of Interaction Mechanisms on Facebook Dynamics Using a Common Knowledge Model,” The 9th International Conference on Complex Networks and their Applications (ComplexNetworks), 2020.

<<<  the end >>> 

@dmachi @ssravi-1984

**Comment by Abhishek001005** [comment]
@cckuhlman @dmachi 
I have made all the changes that you have requested and committed the code in master branch .

Thanks,
Abhishek

**Comment by cckuhlman** [comment]
Can you please make the following changes:

1.  Remove the first two works under (just comment them out, do not lose them):
      -  Publications Related to CINES
              -I. Works on cyberinfrastructure :
    - I ask that these be commented out, not deleted, because they may go back later, but right now, they do not belong.

2. The first of the two to remove (comment out) is funky.
    - The first authors got moved to the end of the reference.  The following should be at the **start** of the ref:  E. Abdelhamid, R. Alo, S. M. Arifuzzaman, P. Beckman, M. H. Bhuiyan, K. Bisset, E. A. Fox, G. C. Fox, K. Hall, S. M. S. Hasan, A. Joshi, M. Khan, C. J. Kuhlman, S. Lee, J. P. Leidig, H. Makkapati, M. V. Marathe, H. S. Mor
    - This way, the "Mor" gets mated up with the "tveit"

3.  These four references appear consecutively in the current listing.
     -  please make a new subsection under major heading "Publications Related to CINES" 
     -  The name of the new subsection should be:  "III.  Software and Analyses to Support net.science Computational Codes"
     -  Move these four references below under this new subheading.
  
Jiayu Li, Fugang Wang, Takuya Araki, Judy Qiu, “Generalized Sparse Matrix-Matrix Multiplication for Vector Engines and Graph Applications,” presented at the MCHPC’19: Workshop on Memory Centric High Performance Computing of SC'19 conference, Denver, Colorado.

Langshi Chen, Jiayu Li, Cenk Sahinalp, Madhav Marathe, Anil Vullikanti, Andrey Nikolaev, Egor Smirnov, Ruslan Israfilov, and Judy Qiu, “SubGraph2Vec: Highly-Vectorized Tree-like Subgraph Counting,” presented at the 2019 IEEE International Conference on Big Data, Los Angeles, CA

K. Xu, W. Hu, J. Leskovec, S. Jegelka,"How Powerful Are Graph Neural Networks?," ICLR, 2019.

MASA: Motif-Aware State Assignment in Noisy Time Series Data. S. Jain, D. Hallac, R. Sosic, J. Leskovec, KDD Workshop on Mining and Learning from Time Series, KDD, 2019

4.  Please remove the space before the colon in heading "I. Works on cyberinfrastructure :"

Thanks guys.

**Comment by cckuhlman** [comment]
Please change the name of the major heading "Publications Related to CINES" to "Publications Related to the Net.Science Cyberinfrastructure"

**Comment by Abhishek001005** [comment]
@cckuhlman @dmachi 

I have incorporated all the changes mentioned above   .

//  Have one  query.

"The first authors got moved to the end of the reference. The following should be at the start of the ref: **E. Abdelhamid**, R. Alo, S. M. Arifuzzaman, P. Beckman, M. H. Bhuiyan, K. Bisset, E. A. Fox, G. C. Fox, K. Hall, S. M. S. Hasan, A. Joshi, M. Khan, C. J. Kuhlman, S. Lee, J. P. Leidig, H. Makkapati, M. V. Marathe, H. S. Mor"

One of the name you have mentioned  above as "E. Abdelhamid" , but referring   second point under "I. Works on cyberinfrastructure:" it is  given as  "S.E . Abdelhamid"  so I have kept as same as there in the second point  "S.E . Abdelhamid" .

Please confirm and let me know if any  changes required  .


Thanks,
Abhishek

**Comment by cckuhlman** [comment]
Hey Abhishek:

You are correct.  I missed this.  Both instances should be "S. E. Abdelhamid".  Sorry I did not copy over correctly the "S" and thanks for catching my mistake.

chris

**Comment by cckuhlman** [comment]
Hey Abhishek:

Thanks for catching this.  I added a comment to the issue. (Do not know how quickly the system alerts you, so am writing.)

chris
________________________________

**Comment by Abhishek001005** [comment]
@cckuhlman 

Thanks for the confirmation .
I have committed the code in the  master branch please have a look and let me know if any further changes is required.

Regards,
Abhishek
