### ISSUE TITLE
Merge Failed

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#126]
I merged the branches into main today, but I am not able to get the system to run.   There are a ton of warnings, but most importantly when I try to run I get this error:
![Net Science 2021-02-12 16-23-08](https://user-images.githubusercontent.com/190574/107823928-9afbc500-6d4e-11eb-9179-86260af182f1.png)

When I first merged and try to run, it failed to compile because of a missing package called react-confirm-alert.  So I installed that package with yarn add react-confirm-alert.  After that, it does run but then I get the error above and eslint is showing tons of warnings in vscode. 

Can you ask the team what is going on and if there are any missing codes?

**Comment by dmachi** [comment]
Also, I'm not sure how to "configure" the system.  I would expect a configuration file somewhere where I can set the URL for the various sciduct services.  I am trying to run this locally and point at my local development instance of sciduct.

**Comment by Abhishek001005** [comment]
@dmachi 
Hi Dustin,
 
We have checked out the code from the master branch and the application is working fine in our environment. As per our understanding, one of the possibilities of the above mentioned error is the mismatched version of Node or if Vs-code is not updated.
   
Following is the configuration for node and vs code that is used for Net.Science.

- Node version : V11.4.0 or V10.14.0

- Vs code : 1.53.0 

  
Please check the version that you have and try upgrading if required. Once done, please follow the below mentioned steps 

- git clone (from master branch)

- npm install

- yarn start

Please let us know if this works fine else we can look at it over the call tomorrow.

**Comment by dmachi** [comment]
I did eventually get it to work after the adjustment of some of the dependencies.  I also added the urls to .env and fixed all of the occurrences where static urls were being defined.  Note that changes to the .env file require a full restart of the app.
