### ISSUE TITLE
Folders without a trailing slash

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#127]
When the url doesn't contain a trailing slash, folders do not load in the file manager.  The decision on whether to show a file tree or not should not be based on whether or not the url has a trailing slash.  Instead, the base path (no slash) should be loaded and its metadata inspected.   It is based on the type (and is_container) should determine what "viewer" is displayed.  If the target item is a folder (actually is_container==true), then the page should be rendered as a file tree, if not it should be rendered as a file viewer (or a message that says files of this type are not viewable in the interface.

I also note that the error message for types that have no viewer says "this file type is not supported".  I think those words are too strong...the filetype is supported explicitly by the system, just not a viewer.  The error message should be corrected to "Unable to preview files of this type.  Click here to download."

**Comment by murli1201** [comment]
The dependency on trailing slash is removed for files as well as folders now. Folders as well as files can be loaded with or without slash. isContainer property is checked for them and based on it the logic works now.
