### ISSUE TITLE
Viewers need to ensure they are loading the file content not the file metadata.

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#128]
JSON Viewer needs to ensure it is loading the file content.  It is currently rendering the metadata about a file instead.  To ensure that the content being download is the actual content, the files should be downloaded from the server by specifying accept: application/octet-stream regardless of the type of data inside of the file.

**Comment by murli1201** [comment]
I changed the accept type as u said me. But I am getting same response as before.
New config for json-
 var config = {
  method: 'get',
      url: `https://sciduct.bii.virginia.edu/filesvc/file/${props.fileId}`,
      headers: {
        'Accept': 'application/octet-stream',
        'Authorization': token
      },
   };

I am also attaching the screenshots for both of them-


![Accept (new)](https://user-images.githubusercontent.com/54397265/108688004-6ab9e080-751d-11eb-99dd-ea57dfea8eef.png)
![Accept (old)](https://user-images.githubusercontent.com/54397265/108688011-6d1c3a80-751d-11eb-9f69-ae60b023d4a6.png)

**Comment by murli1201** [comment]
@dmachi 

I also checked previewing and downloading various JSON files. I got the correct data instead of metadata for all the files in both the cases.

**Comment by murli1201** [comment]
I have replaced accept: */* to accept: application/octet-stream for all the API's to preview and download files and we can get correct data rendered instead of metadata now.
