### ISSUE TITLE
Filter on job listing page is not returning filtered list.

### ISSUE THREAD

**Issue by Abhishek001005** [NSSAC/CINES#139]
@dmachi 
If the users applies the filter on job listing page, they do  not get the filtered list, instead get below mentioned error message.

Query parameter: - https://sciduct.bii.virginia.edu/js/job_instance?&in(state,(Completed))&limit(10,0)&sort((-creation_date))
Response :-
**message: "tuple index out of range", status: 500}
message: "tuple index out of range"
status: 500**

**Comment by dmachi** [comment]
This is an invalid query.  Notice the two paranthesis in sort().  Please check and see if this is still failing when fixed.

**Comment by murli1201** [comment]
Fixed.
