### ISSUE TITLE
Job output is creating folder instead of file

### ISSUE THREAD

**Issue by Abhishek001005** [NSSAC/CINES#142]
@dmachi 
On submitting the jobs that have output name and output container - e.g. snap_CntDegNodes type of jobs, the job does complete - but the output file mentioned in the form is saved as a folder and not a file in file manager .

note:- I am facing some issue while attaching the screenshots so sending the same on email for more clarity .

**Comment by dmachi** [comment]
Yes, this is what I was trying to describe in my previous response to Annapurna.  The cases where there should be _no_ file output have that empty folder.  You are showing the output name/container  because output_files is defined and it shouldn’t be in this case.  Please make sure, however, that your check for “output_files” looks to see that output_files.type exists.  If there is no output to be generated (so no need to ask for output container/name), it will be output_files: {} (an empty dictionary)

I will get the definitions regenerated and uploaded soon.

**Comment by Abhishek001005** [comment]
@dmachi 

Tried running a job with appropriate output_file.type and got the below error(net.science/snap_GetSccs)
   Begin Staging
********************
Reading Job Information from job.json
Retrieving 130 bytes in 1 file
Retrieving file from https://sciduct.bii.virginia.edu/fs/file/0b1a4f86-a885-47b4-ae55-d62740c39e82/1
Downloaded file to input/inputFile_Graph
*******************
    End Staging
*******************
*********************
    Begin Primary
*********************
   ==== echo inputs ====
  name of graph file containing graph to operate on.:  /input/inputFile_Graph
  graph type is Snap type, so one of:  PNGraph, PUNGraph, PNEANet.:  PNGraph
  col index in graphName for the src (source) node of the edge (src, des).:  0
  col index in graphName for the des (destination) node of the edge (src, des).:  1
  output file name for variable CnComV:  /output/outputFile_CnComV.out
   ==== end echo ====

  Time to complete analysis (s, hr):  0.030777454376220703 8.549292882283529e-06
 ----- good termination -----
*********************
    End Primary
*********************
*********************
  Begin Completion
*********************
Reading Job Information from job.json
Reading Job Definition Information from job_definition.json
Creating file 'GetInDegCnt_directedgraph_output' [snap_TCnComV] at https://sciduct.bii.virginia.edu/fs/file/home/Annapurna/GetInDegCnt_directedgraph_output
Error pushing files to FileService: Error while creating container instance 'GetInDegCnt_directedgraph_output' [snap_TCnComV] at https://sciduct.bii.virginia.edu/fs/file/home/Annapurna/GetInDegCnt_directedgraph_output
req: {'id': 0, 'jsonrpc': '2.0', 'method': 'delete', 'params': ['/home/Annapurna/GetInDegCnt_directedgraph_output/GetInDegCnt_directedgraph_output', True]}
URL: https://sciduct.bii.virginia.edu/fs
Error cleaning up {"id":0,"result":{"args":[{"args":["Not Found"],"quiet":true,"status_code":404}],"message":"Not Found","status":404}}
response: {"id":0,"result":{"args":[{"args":["Not Found"],"quiet":true,"status_code":404}],"message":"Not Found","status":404}}

**Comment by dmachi** [comment]
Ok.  I don’t think all the snap file types have been added to the new file service.  Will check on that.  Thanks.

**Comment by dmachi** [comment]
Yes, those snap types weren’t in there yet.  I have added them now.

You can get all the types back with ```curl -H "accept: application/json" "https://sciduct.bii.virginia.edu/fs/type/“```

Dustin

**Comment by Annapurna-Kupast** [comment]
We checked and the snap types are not added in the array. Please see for your reference

{​args: [{​args: [,…], quiet: true, status_code: 400}​],…}​
args: [{​args: [,…], quiet: true, status_code: 400}​]
0: {​args: [,…], quiet: true, status_code: 400}​
args: [,…]
0: "Failed Validation: 'snap_graph' is not one of ['folder', 'testContainer', 'testContainer2', 'testContainer3', 'symlink', 'json', 'text', 'png', 'jpg', 'pdf', 'xml', 'csv', 'excel', 'jsonh+fasta', 'na+fasta', 'aa+fasta', 'fasta', 'geographical_region', 'population_network+text', 'population+text', 'epihiperOutput', 'epihiper_cell_output', 'epihiper_multicell_analysis', 'igacat-threat+json', 'exceads_intervention_template']"
quiet: true
status_code: 400
message: "Failed Validation: 'snap_graph' is not one of ['folder', 'testContainer', 'testContainer2', 'testContainer3', 'symlink', 'json', 'text', 'png', 'jpg', 'pdf', 'xml', 'csv', 'excel', 'jsonh+fasta', 'na+fasta', 'aa+fasta', 'fasta', 'geographical_region', 'population_network+text', 'population+text', 'epihiperOutput', 'epihiper_cell_output', 'epihiper_multicell_analysis', 'igacat-threat+json', 'exceads_intervention_template']"
status: 400

**Comment by Annapurna-Kupast** [comment]
We also tried running jobs (e.g. snap_GetKCoreNodes) where the output.files had the following schema:

output_files: {associateJobMeta: true, file: "outputFile_CoreIdSzV.out", isContainer: false, type: "snap_TIntPrV"}
associateJobMeta: true
file: "outputFile_CoreIdSzV.out"
isContainer: false
type: "snap_TIntPrV"

and these jobs are failing. Would these types also need to be added in the array for the jobs to complete?

**Comment by dmachi** [comment]
I think there is a different issue causing this.  I will take a look and get it fixed.

**Comment by dmachi** [comment]
This has been updated and is working for me now for both of these cases. Please test again.
