### ISSUE TITLE
Non output container forms is not returning correct results.

### ISSUE THREAD

**Issue by Annapurna-Kupast** [NSSAC/CINES#143]
For forms like - snap_CntInDegNodes, the output is expected to be an integer and there should be no output definition, however there is an output definition and though the job completes the output data (expected integer) is not returned instead is returning the output container.

**Comment by dmachi** [comment]
I have fixed the missing output.  Note as a correction that there can actually be both output and output_files, though I'm not sure if we actually do that in snap or not.
