### ISSUE TITLE
Getting error while submitting job for a methods having fields with type float

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#145]
@dmachi 

Hi Dustin,
 For a few methods like snap_GetBetweennessCentr, snap_GetPageRank and  snap_GetEigenVectorCentr, we are getting an error with 'Unknown type "float"' and status: 500, maybe because they have float type properties in the input schema.

I have also attached screenshots for your reference.

As you can see in one of the screenshots, the response status on submission is 200 OK, which forces a success toaster on UI, instead of showing an error toaster. Please have a look into this issue.

**Comment by dmachi** [comment]
I will check on the error to ensure that it returns a proper status code.  I have passed along the schema errors so they get fixed too. Thanks.

**Comment by dmachi** [comment]
I have uploaded the image with the updated schema so there should be no more floats in the schema.  You can retest those methods.  I have not yet addressed the lack of error when validation fails.

@murli are you submitting by posting a job instance or using the json-rpc method?

**Comment by dmachi** [comment]
What are you sending.  Are you sure you aren’t sending this as a string?

The both seemed to work for me.

(sciduct_env) bash-4.2$sciduct job submit -d net.science/snap_GetBetweennessCentr -o /home/djmTest1 -n anothertest IsDir=false srcCol=0 desCol=1 graphType=PUNGraph NodeFrac=1.0 inputFile_Graph=/home/djmTest1/test2
34be513f-0514-41f3-ab3d-7ba0e97110e6

(sciduct_env) bash-4.2$sciduct job submit -d net.science/snap_GetBetweennessCentr -o /home/djmTest1 -n anothertest2 IsDir=false srcCol=0 desCol=1 graphType=PUNGraph NodeFrac=12 inputFile_Graph=/home/djmTest1/test2
9cb63ace-db3a-4aa9-b279-1709a8753eb6

If I look at the input, I can confirm that it is indeed a number not a string.

(sciduct_env) bash-4.2$sciduct job show 9cb63ace-db3a-4aa9-b279-1709a8753eb6 --json | jq .input
{
  "IsDir": false,
  "srcCol": 0,
  "desCol": 1,
  "graphType": "PUNGraph",
  "NodeFrac": 12,
  "inputFile_Graph": "/home/djmTest1/test2"
}

Can you confirm?  If it isn’t a string, please let me know which specific method you are testing and send me input you are sending.

**Comment by murli1201** [comment]
You are right, it was a mistake from our side. The value was passed as a string. The logic to convert the value into float was missing. I have handled that now and the job has submitted successfully.
