### ISSUE TITLE
Getting 'This Job Definition is currently disabled" message on submitting few jobs.

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#146]
@dmachi

Hi Dustin,
For a few methods, we are getting an error- {message: "This Job Definition is currently disabled", status: 503} when trying to submit a job instance and these jobs are not listed on the UI.

Some of the methods found with this issue are snap_GetBfsEffDiam, snap_GetBfsFullDiam, CommunityCNM, GetWccSzCnt, GetWccs, snap_GetMxScc, snap_GetMxWccSz, snap_GetNodeInDegV, snap_GetNodeOutDegV.

**Comment by dmachi** [comment]
I just updated the methods that weren't yet enabled, so these should be good now.
