### ISSUE TITLE
Few jobs are getting failed with "Error pushing files to FileService" error.

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#147]
@dmachi

Hi Dustin,
For a few methods like snap_GenPrefAttach_, snap_GenSmallWorld, the jobs are getting failed as the output file cannot be created in the container.

I have attached the std out for method snap_GenPrefAttach for reference-

********************
   Begin Staging
********************
Reading Job Information from job.json
No files to stage.
*******************
    End Staging
*******************
*********************
    Begin Primary 
*********************
   ==== echo inputs ====
  The number of nodes desired.:  10
  The out degree of each node desired.:  2
  output file name for variable libraryMethodReturnTypeVariable:  /output/outputFile_libraryMethodReturnTypeVariable.out
   ==== end echo ====
 
  Time to complete analysis (s, hr):  0.02454972267150879 6.819367408752441e-06
 ----- good termination -----
*********************
    End Primary 
*********************
*********************
  Begin Completion
*********************
Reading Job Information from job.json
Reading Job Definition Information from job_definition.json
Creating file 'genpref.out' [undirected_graph] at https://sciduct.bii.virginia.edu/fs/file/home/Rakesh
Error pushing files to FileService: Error while creating container instance 'genpref.out' [undirected_graph] at https://sciduct.bii.virginia.edu/fs/file/home/Rakesh 
req: {'id': 0, 'jsonrpc': '2.0', 'method': 'delete', 'params': ['/home/Rakesh/genpref.out', True]}
URL: https://sciduct.bii.virginia.edu/fs
Error cleaning up {"id":0,"result":{"args":[{"args":["Not Found"],"quiet":true,"status_code":404}],"message":"Not Found","status":404}}
response: {"id":0,"result":{"args":[{"args":["Not Found"],"quiet":true,"status_code":404}],"message":"Not Found","status":404}}

**Comment by dmachi** [comment]
I will check on these.  The type "undirected_graph" is incorrect and may have gotten reverted.

**Comment by dmachi** [comment]
These should be fixed.  Tested with GenSmallWorld.

**Comment by Annapurna-Kupast** [comment]
Verified the 4 methods mentioned below that were failing with the same error. They are all completing successfully and the output is matching with what is mentioned in GitHub.

- snap_GenPrefAttach
- snap_GenSmallWorld
- snap_GenConfModel
- snap_GenDegSeq

**Comment by murli1201** [comment]
Hi Dustin,
For method snap_GetClustCfAll, the jobs are getting failed as the output folder cannot be created in the container.

I have attached the std out for method snap_GetClustCfAll for reference-

********************
   Begin Staging
********************
Reading Job Information from job.json
Retrieving 166 bytes in 1 file
Retrieving file from https://sciduct.bii.virginia.edu/fs/file/b7fe970f-d22d-4e13-a1c6-cc58a7eb895b/1
Downloaded file to input/inputFile_Graph
*******************
    End Staging
*******************
*********************
    Begin Primary 
*********************
   ==== echo inputs ====
  name of graph file containing graph to operate on.:  /input/inputFile_Graph
  graph type is Snap type, so one of:  PNGraph, PUNGraph, PNEANet.:  PNGraph
  col index in graphName for the src (source) node of the edge (src, des).:  0
  col index in graphName for the des (destination) node of the edge (src, des).:  1
  If !=-1 then compute clustering coefficient only for a random sample of SampleNodes nodes:  -1
  output file name for variable DegToCCfV:  /output/outputFile_DegToCCfV.out
  output file name for variable libraryMethodReturnTypeVariable:  /output/outputFile_libraryMethodReturnTypeVariable.out
   ==== end echo ====
 
  Time to complete analysis (s, hr):  0.02551865577697754 7.088515493604872e-06
 ----- good termination -----
*********************
    End Primary 
*********************
*********************
  Begin Completion
*********************
Reading Job Information from job.json
Reading Job Definition Information from job_definition.json
Creating container instance 'GetClustCfAll' [folder] at https://sciduct.bii.virginia.edu/fs/file/home/Annapurna/Test/
Creating file 'outputFile_DegToCCfV.out' [snap_TFltPrV] at https://sciduct.bii.virginia.edu/fs/file/d6ff38ff-2554-40e2-accf-a3021537e0f2
Creating file 'outputFile_libraryMethodReturnTypeVariable.out' [list_primitive_dataType] at https://sciduct.bii.virginia.edu/fs/file/d6ff38ff-2554-40e2-accf-a3021537e0f2
Error pushing files to FileService: Error while creating container instance 'outputFile_libraryMethodReturnTypeVariable.out' [list_primitive_dataType] at https://sciduct.bii.virginia.edu/fs/file/d6ff38ff-2554-40e2-accf-a3021537e0f2 
req: {'id': 0, 'jsonrpc': '2.0', 'method': 'delete', 'params': ['/home/Annapurna/Test/GetClustCfAll', True]}
URL: https://sciduct.bii.virginia.edu/fs
response: {"id":0,"result":"OK"}

**Comment by dmachi** [comment]
Thanks.  This is failing when it tries to create a file of “list_primitive_dataType”.  I will check with Chris and Lucas on this and either get it fixed or add it to the fileservice as appropriate.
