### ISSUE TITLE
For any error while submitting job, the correct status and message is found in preview instead of response status.

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#148]
@dmachi 

Hi Dustin,
For any kind of error produced while submitting the job, the response status is 200 OK. To find the reason for getting error, user needs to check it in the preview section of API called. Instead of getting response status 200 we should get the original status as why the job is failed. It will also help in rendering the proper toaster on the UI. This issue is observed for any type of error while submitting the job like 400,402,403,etc.

I have hereby attached an screenshot trying to explain the issue. 
![Screenshot (42)](https://user-images.githubusercontent.com/54397265/111130191-eba84d00-859c-11eb-9d3d-4cf1f320eceb.png)
![Screenshot (43)](https://user-images.githubusercontent.com/54397265/111130199-ee0aa700-859c-11eb-8ce5-21be96be764c.png)

**Comment by dmachi** [comment]
I believe I have this fixed.  Please let me know if you see it happening anywhere else.

**Comment by murli1201** [comment]
Yes, Dustin. I checked this for various errors and it is fixed. 

Thank you.
