### ISSUE TITLE
Delete API is not working.

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#150]
The delete API is not working when trying to delete any of the files.
 var config = {
          method: 'delete',
          url: `${process.env.REACT_APP_SCIDUCT_FILE_SERVICE}/file/${props.fileId}?recursive=true`,
          headers: { 
            'Accept': '*/*',
            'Authorization': token
          },
       }

The status goes to 'Pending' and after 5 - 10 minutes it gives 500 Internal server error.
{
"args": [
  {
"args": [],
}
],
"message": "",
"status": 500
}

**Comment by dmachi** [comment]
I was getting this failure only on deletion of directories, but not on deletion of files.  This was returning a Forbidden error because the request made via HTTP (instead of RPC) was ignorning the ?recursive=true.  This has been fixed and deleting is working for me.

**Comment by murli1201** [comment]
The delete API is not working even for files for us. I have attached an screenshot in which both delete and download API's get into pending state. This was working fine before yesterday.



https://user-images.githubusercontent.com/54397265/115531568-8ee23580-a2b2-11eb-8d7d-e77796bf42f1.mp4

**Comment by dmachi** [comment]
This has nothing to do with uploading. I'm closing this ticket in favor of a common one tracking the problem seen here: #153
