### ISSUE TITLE
Download API not working

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#151]
The download API is not working when trying to delete any of the files.
  var config = {
          method: 'get',
          url: `${process.env.REACT_APP_SCIDUCT_FILE_SERVICE}/file/${props.fileId}`,
          headers: { 
            'Accept': 'application/octet-stream',
            'Authorization': token
          },
          responseType: 'blob' 
       };
The status goes to 'Pending' and after 5 - 10 minutes it gives 500 Internal server error.
{
"args": [
  {
"args": [],
}
],
"message": "",
"status": 500
}

**Comment by dmachi** [comment]
I don't understand what the download API has to do with this?  If the file is deleted, you can't download it.  Are you saying the deleting is failing?  There was an error when you tried to download a file that doesn't exist, and I have fixed that so that it returns a Not Found reponse.

**Comment by murli1201** [comment]
This issue is a different one. We are not trying to download the file we deleted. When we try to download any file, this issue is faced.

 I am attaching the same screenshot attached in https://github.com/NSSAC/CINES/issues/150. for reference.


https://user-images.githubusercontent.com/54397265/115532003-0021e880-a2b3-11eb-97a8-9bb104f23548.mp4

**Comment by dmachi** [comment]
This has nothing to do with uploading. I'm closing this ticket in favor of a common one tracking the problem seen here: #153
