### ISSUE TITLE
DiskFileStore stops responding

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#153]
Sometimes the diskfilestore stops responding which causes request to the fileservice to hang and ultimately fail.  This never happens when running directly. I have only been able to reproduce this when running with multiple Uvicorn processes via supervisord.   I have made some changes to that part of the setup and have been able to successfully upload/delete/download and so far have avoided the locking situation. 

Please update this ticket if you see this happening.

**Comment by murli1201** [comment]
Hi Dustin,
I am able to successfully upload/delete/download files now.

Thank you.
