### ISSUE TITLE
File Size in File Manager after Upload

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#154]
I've been trying to trace the issue with the file size not showing up after a successful upload.  This rarely happens for me, but if I try to upload many files and I throttle the upload speed to "slow 3g" I can get it to happen.

I noticed that in this case, if I refresh the page, the file size is shown.   I did some debugging to ensure that the server was in fact returning the file metadata, including the size after the successful PUT operation.  Then I tried to confirm in the browser.  While chrome will not show the response due to an existing bug ( https://stackoverflow.com/questions/38924798/chrome-dev-tools-fails-to-show-response-even-the-content-returned-has-header-con),  it does appear to be successful.  To ensure this, I added a console log after the PUT operation so that it would show the response data.  So I can confirm that the size in the folder listing will sometimes show blank, even though the PUT was successful and had the size in the response.  Perhaps the folder refresh is being triggered too soon?

Here you can see the file listing after successful upload, shows no size for one of the files
![Net Science 2021-04-21 12-42-25](https://user-images.githubusercontent.com/190574/115590534-12922700-a29f-11eb-8de7-799a07e6f8d5.png)

You can see in Chrome that the request succeeded with at 200 response and a size:
![ 2021-04-21 12-43-27](https://user-images.githubusercontent.com/190574/115590702-453c1f80-a29f-11eb-8fb7-cb76e52c4c6e.png)

Here is the response tab from the above request in Chrome
![ 2021-04-21 12-44-59](https://user-images.githubusercontent.com/190574/115590869-76b4eb00-a29f-11eb-91bb-44d5799c2d03.png)

Here is the console, where I've added a console.log to dump the response.  You'll notice it does have a size associated with it:
![ 2021-04-21 12-46-16](https://user-images.githubusercontent.com/190574/115591056-b24fb500-a29f-11eb-82ff-8894ce3a90f8.png)

My guess is that there is a race condition in the client code, but I haven't tried to actually debug that.  I think this is a distinct issue from #153 , though this issue could also happen when that one does.

**Comment by murli1201** [comment]
Fixed
