### ISSUE TITLE
GenRandomSeedSets for CSonNet are failing

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#159]
```
The following have been reloaded with a version change:
  1) singularity/3.7.1 => singularity/3.5.2
 
Traceback (most recent call last):
  File "/csonnet-input-file-generation/inital_states_file/pure-random/src-v01/genRandomSeedSetsCsonnet.py", line 277, in <module>
    idx = random.randint(0,total-1) #Inclusive
  File "/usr/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
srun: error: udc-aj36-4c0: task 0: Exited with exit code 1
srun: Terminating job step 21821673.1
```

**Comment by cckuhlman** [comment]
See issue #3 here:  https://github.com/NSSAC/csonnet-input-file-generation/issues

This is the repo that contains the code that is failing.

The code has been corrected, but needs to be re-containerized and re-integrated into net.science, per the message there.

**Comment by cckuhlman** [comment]
@dmachi 

Is this handled ok?  That is, putting an issue in the repo that has the code, and then cross-referencing?

**Comment by dmachi** [comment]
Yep, this is fine.  I'll note that your reference to this ticket in the other one is automatically added to this one.
![CINES 2021-04-30 10-52-28](https://user-images.githubusercontent.com/190574/116712750-2c6bf200-a9a2-11eb-9db3-5191bf8b9f34.png)

**Comment by Lucaslhm** [comment]
Submodule updated in Cines-Snappy-Generated Eon-Cines branch to reflect the changes to csonnet-input-file-generation.

**Comment by dmachi** [comment]
I've pushed a new image with @cckuhlman 's updates.  @murli1201, can you test again please?

**Comment by murli1201** [comment]
Hi Dustin,

I tested it for SEIR sub models. The jobs are now getting completed.

Thank you.
