### ISSUE TITLE
Job cancellation API gives 200 OK response when trying to cancel Completed/Failed jobs.

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#164]
Hi Dustin,

I am testing the job cancellation API to allow user to cancel the running jobs. The API works correctly when trying to cancel jobs which are in queue/ running. 

But, when I try cancelling a job which is either completed or failed, the API gives 200 OK response, but the job status is not changed. (The job status should not change and this is the correct behavior). But, in this case, it would be great if the API gives an error as response instead of 200 OK. It would be easier to handle this scenario on the UI if this is handled.

I have attached the screenshots of the API parameters, response and body when trying running it for a Completed job.

_Note- There would not be 'Cancel' button for completed/ failed jobs on the UI, but the above scenario will be observed if a user tries cancelling a running job and the job gets completed/ failed when the cancellation pop up is open._

![Screenshot (71)](https://user-images.githubusercontent.com/54397265/118277728-b78ed100-b4e6-11eb-98c9-478a02e3c6c2.png)
![Screenshot (72)](https://user-images.githubusercontent.com/54397265/118277739-ba89c180-b4e6-11eb-9636-603cb336f026.png)

**Comment by dmachi** [comment]
Ok, I’ve added this to my list.

**Comment by murli1201** [comment]
It is working now as expected. Thank you, Dustin.
