### ISSUE TITLE
Cancel API gives 200 OK response but the job gets completed successfully.

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#173]
Hi Dustin,

When trying to cancel a job, the cancel API gives response 200 OK, but the job gets completed successfully. It is usually observed when a user tries cancelling a job at the same time when it is near to its completion.

_**Note-  This issue is not observed very frequently. Currently, as job take very less time to complete, this may be observed.**_ 

I have attached the screenshots for this issue. I tried cancelling job with Id '52cef3fd-fe69-48d5-a5bf-b4bf568f99ca'. Please have a look.

![Screenshot (75)](https://user-images.githubusercontent.com/54397265/119815316-0a19b580-bf09-11eb-9b3a-06345e3e12a5.png)
![Screenshot (74)](https://user-images.githubusercontent.com/54397265/119815331-0d14a600-bf09-11eb-85af-db83cbd57c5f.png)

To handle this, If completion and cancellation are executed at the same time, which should be given priority needs to be decided.

Thank you,
Murli.

**Comment by dmachi** [comment]
I don't see this as a problem.  If you ask for a job to be cancelled and it finishes before that cancellation is processed, it will end up completed (or failed). As you mentioned, this is more likely to happen on short test jobs.  The UI should just report the state that the backend says it is in.

**Comment by murli1201** [comment]
Thanks for confirming, Dustin.
