### ISSUE TITLE
Simulation Job Resubmission

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#175]
When I click the resubmit button on a previous simulation job, the right hand side is filled out, but the left hand side (model specific) is not.

![Net Science 2021-06-03 10-35-30](https://user-images.githubusercontent.com/190574/120662919-88b9aa00-c457-11eb-8ec0-b48a26dbe340.png)

**Comment by murli1201** [comment]
Hi Dustin,

In case of CSonNet Simulation model, we submit the dynamic part of the job in the form of rules. These rules do not include data regarding the dynamic values such as-
- Behavior Model
- Sub model (if present)
- dynamic fields (e.g.- threshold value, edge probability, exposed duration, etc. )

When trying to resubmit, all the above fields are required.
In the **old** CSonNet Simulation jobs that were submitted - as these fields are not present in the input schema it is difficult to autofill these fields when trying to load the form for resubmission.

I have updated the logic where all these fields are stored in an object **'dynamic_inputs'** when user submits a job. Please see the screenshot. Once the new submit API starts working, all the simulation jobs will work as expected on resubmission (All the fields will be filled out).

<img width="571" alt="dynamic_input" src="https://user-images.githubusercontent.com/54397265/120763674-15866580-c535-11eb-8b92-8d7c097638d9.PNG">

Thank you.

**Comment by dmachi** [comment]
I see, I get the reasoning.

Do you mean you are actually going to pass “dynamic_inputs” to the job service so that you can get that data back when you reinspect the job?

**Comment by murli1201** [comment]
Yes, right.

**Comment by dmachi** [comment]
This seems to be working now.
