### ISSUE TITLE
file init

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#189]
When Lucas logged into net.science for the first time today, it did not seem to issue the file init that would initiate the creation of his home directory and let you know what his homedirectory is.  This should generally happen automatically when the application starts and the user is logged in (or after they have logged in otherwise).   It is also how the application can know what the user's homedirectory is so that we can default to that for some actions.

**Comment by murli1201** [comment]
Hi Dustin,

I have made default file manager path to '/home' changes as you asked in the mail. I have also made the necessary changes related to this git issue(initiate a new user) for the new code. I have merged these changes to the master. Please have a look.

Thank you.

**Comment by dmachi** [comment]
Confirmed working today.
