### ISSUE TITLE
Login status not very robust

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#191]
The past week or so the authentication has seemed more flaky (though perhaps this is just because of more use).  The auth itself seems to work fine, but the app doesn't seem to reliably log one out when the token is expired or, if the application is still active, it doesn't seem to refresh the token automatically.    I've noticed a few cases where I was actively doing something or had within the previous 15 mins and things just stop working because the token is expired and/or missing. 

I wonder if this could be an artifact of having the app open in multiple browser windows.

**Comment by murli1201** [comment]
We are trying to reproduce this issue since morning. But, we are not able to reproduce this. Will keep trying tomorrow and give you the updates.
