### ISSUE TITLE
Metadata Sidebar

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#192]
I know that the metadata sidebar work is still being done, however I just noticed that you cannot scroll vertically inside of that panel any more.  As you work on this code, please make sure the scrolling part works too.

**Comment by dmachi** [comment]
@murli1201  thanks for the addition of the creation and modified dates.  I would like to see these fields displayed when they exist:

- created_by
- completed_date (this is also populated for a failure)
- exit_code 
- failure_type
- cancelled_date
- status

Note that status is generally a dictionary, like:
```
  "status": {
    "staging": {
      "progress": 100,
      "message": "Staging completed",
      "timestamp": "2021-06-16T23:28:04Z"
    },
    "primary": {
      "message": "Running plot_degree_distribution_sciduct",
      "timestamp": "2021-06-16T23:28:04Z"
    },
    "completion": {
      "progress": 100,
      "message": "Job Completed",
      "timestamp": "2021-06-16T23:28:06Z"
    }
  },
```

**Comment by dmachi** [comment]
Ravi also like the color update for the links in the file service.  Can you use that same color for other links such as those in the job metadata panel?

**Comment by murli1201** [comment]
Yes, I am making those color changes in the metadata section too for the job panel too. 

I will also add all the new fields mentioned above in the metadata when they exist.

Thank you.

**Comment by murli1201** [comment]
Hi Dustin,

I have made the color changes as well as medatata changes and merged to the master.

Thank you.

**Comment by dmachi** [comment]
Fixed
