### ISSUE TITLE
Preview read permissions

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#194]
There is a problem with viewing or downloading files with "public" permissions.  If a file has "public": true, then it is viewable (and downloadable) by anyone, including users who are not logged in.  I can't find any checks for this in the code and I don't quite understand how permission are being checked in here...it is doing something with local storage.

Specifically, files in https://alpha.net.science/apps/files/resources/net.science/workshop_v1/ should be viewable by everyone.

This is an important issue to fix.  Tomorrow morning I will temporarily grant read privileges to "*" until this issue is fixed.  This will help logged in users see these files, but it wont' help guest users.

**Comment by murli1201** [comment]
Hi Dustin,

We were not checking the 'public' property for preview/ download. But, I have now added the conditions to check if a file is public. I will commit and merge those changes by today to master. Hence, you dont need to make any changes from the backend. After the commit, our QA team as well as you both can verify if the changes are working as expected. 

Thank you.

**Comment by murli1201** [comment]
I have fixed this issue and merged to the master.

**Comment by dmachi** [comment]
This mostly worked.  One case did not.  When not logged in, I was able to click on the file and did not get the permission error, but nothing was rendered either.  I could see the file transferred in the network tab.

**Comment by murli1201** [comment]
I just missed committing a small change. I have now merged it to master. QA team will simultaneously verify the fix. Please have a look if now it is working as expected.

**Comment by dmachi** [comment]
Confirmed.
