### ISSUE TITLE
Generated forms don't seem to get default values always

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#195]
generate_graph_visualization for example doesn't have any of the default values selected from the input schema.

**Comment by dmachi** [comment]
Still seems empty. Did you commit this code?
![Net Science 2021-06-17 23-59-02](https://user-images.githubusercontent.com/190574/122504288-ffae8100-cfc7-11eb-907a-17689e425749.png)

**Comment by murli1201** [comment]
Hi Dustin, 
I interpreted this issue wrongly. I thought you were talking about the 'graph' field not retaining value on resubmit.

I have fixed this now. I am using the default value on form load. The changes are merged to the master.

**Comment by dmachi** [comment]
Fixed.
