### ISSUE TITLE
Download Types

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#197]
Currently we have a large list of allowable upload types that comes from a query of types from the file service.  Most make no sense for users to upload themselves directly and just make things more difficult.  Please create a configuration option that allows us to define which file types are available in the upload dialogs.   For an initial configuration, we can use ["PUNGraph","PNGraph","PNEANet", "csv","tsv","json","text"].

In the file manager, the generic upload can simply use the list above as the available types.  In the uploader that is built into the file selection in submission forms, we should use the intersection between the configured list above and the type list provided from the job definition.  It currently includes all of the types defined for a particular file in the input files of a job definition, but we only want to allow the subset of those that are also what we configured as allowable uploads.

**Comment by murli1201** [comment]
Hi Dustin,

I have made the changes and merged to the master.

Thank you.

**Comment by dmachi** [comment]
confirmed.
