### ISSUE TITLE
Material for Landing Page for CINES

### ISSUE THREAD

**Issue by ssravi-1984** [NSSAC/CINES#2]
[landing_page_material.pdf](https://github.com/NSSAC/CINES/files/4227586/landing_page_material.pdf)

I have attached a new version of the maerial for the landing page. (A minor revision was done on Feb. 19, 2020.)  I have given below the changes in the new version compared to the previous one.

(a) The material on "Participating Institutions and Organizations" has changed. In the current version, we have the name of the institution (or organization) followed by one or more contacts for the entity.

(b) Names and affiliations of the members of the Scientific Advisory Board have been added to the document.

(c) The part on "Links to Educational Materials on Network Science" has some additions, namely the links to the courses taught by Aaron Clauset, David Kempe, people at Stanford University and Boleslaw Szymanski. Also, please note that for the courses taught by Reka Albert and Albert-Laszlo Barabasi, the correct language accents have been added to their names.

If you have any questions, please contact me. -- Ravi

**Comment by Annapurna-Kupast** [comment]
@ssravi-1984 
Could you please let us know should we add the names and affiliations of the members of the Scientific Advisory Board to section to Publications or Collaborators?

**Comment by ssravi-1984** [comment]
It is best to add the names and affiliations of the Advisory Board
members to
the "Collaborators" section.

   Thanks.

-- Ravi
   ssravi0@gmail.com

**Comment by Annapurna-Kupast** [comment]
@ssravi-1984 
Thank you for confirming Ravi. We have added the members of Advisory Board to Collaborators and have committed the changes to GitHub.
