### ISSUE TITLE
SavePajek No Output File

### ISSUE THREAD

**Issue by hcars** [NSSAC/CINES#200]
I ran the SavePajek function on the jazz network. I requested the output filename as jazz.pajek. The job completed without error, but the output Pajek file is not available in my directory. Is this intentional? If users cannot use the output, it may be best to disable this function for now.

**Comment by dmachi** [comment]
I don't think any of the Save* functions will work.  I'll get them disabled for now.

**Comment by dmachi** [comment]
These have been disabled for now.
