### ISSUE TITLE
 net.science/snap_GetModularity

### ISSUE THREAD

**Issue by hcars** [NSSAC/CINES#201]
One of the input parameters to this method is a file called inputFile_NIdV. This is a required parameter that is described as :

> Computes the modularity score of a set of node ids *NIdV* in *Graph*.

Is there a way to create one of these files in the system? If not, then, this function cannot be executed.

**Comment by dmachi** [comment]
It looks like this file is of type snap_TIntV.  So you could generate that file type with snap_GetNodeWcc, snap_GetNodesAtHop, snap_GetSubGraph, snap_GetArtPoints, snap_GetCmnNbrs (this one has an error in the schema though), snap_GetDegSeqV, and snap_GetDegSeqV1.  There are probably additional places, but that’s as far as I’ve made it through the file before this meeting.
