### ISSUE TITLE
Method "generate_graph_visualization" failed when given output_type as "svg" and "ps".

### ISSUE THREAD

**Issue by Rakesh-persistent** [NSSAC/CINES#204]
When executed method "generate_graph_visualization" with output_type as "svg" or "ps", jobs are getting failed. 
Below are the job id's listed:
1. JOB id for svg file:
fc226e1d-e86f-4d62-bd1f-cf44d1166030
2. JOB id for ps file:
63d2514d-ba05-4c4c-9a71-0867776e1097

Note - When user selects output type as "pdf" or "png" the jobs are completed.

**Comment by dmachi** [comment]
SVG wasn't a valid type.  Neither were .ps and .eps.  I have enabled them all, but I didn't test .ps and .eps.  I did test SVG, but will note that we don't have a viewer in the app for this one.  I am not concerned about not having .ps or .eps viewers, but we should have a .svg viewer.  @murli1201 how hard would it be to enable an svg viewer like we have for png/jpg.

**Comment by murli1201** [comment]
I need to explore a few libraries that can be used to preview svg files in React. I will revert back to you in few hours regarding this.

Thank you.

**Comment by dmachi** [comment]
This is not a huge deal for now if you don’t get it figured out.  I was just thinking it would use the browser’s built in ability to display a svg.

**Comment by murli1201** [comment]
I have added support for 'svg' files preview. It will work for now. But need to work on CSS later on because in the svg files generated, we give static height and width while submitting the jobs. Hence, the alignment while previewing is left aligned.

The changes are merged to the master.

**Comment by dmachi** [comment]
Fixed.  I am not concerned about the css part of this for today.
