### ISSUE TITLE
generate_graph_visualization issue with contract/drop_isolates

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#207]
There is an odd issue with the generate_graph_visualization form.  While the form it self works, even if you set both contract and drop_isolates to true, one of the two properties will always be false in the submitted input.  

For example, in the screen shot below, both contact and drop isolates were toggled to true, but one is false here. 
![Net Science 2021-06-17 22-43-43](https://user-images.githubusercontent.com/190574/122498652-7f831e00-cfbd-11eb-9c21-c4c5a38de027.png)

**Comment by murli1201** [comment]
Hi Dustin,

I have fixed this issue and merged to the master.

Thank you.

**Comment by dmachi** [comment]
Fixed
