### ISSUE TITLE
csonnet code for generating plots from simulation

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#208]
There is a problem with the plotting of results from csonnet.  Job name:  net.science/CSonNet_Plotting

Here are job IDs that can be looked at that result in errors:
b658ec18-0589-4689-ae77-f6ce2d4043a2
aed5b693-9049-4bd1-b2b1-00ff4e84f598

Here are plot file IDs that can be looked at, although the plots themselves are attached.
6b0f6fed-b3c2-4f60-90ba-e3fba8497708
d693d749-523f-475e-b38f-1165c8799c8a
1b771cb6-e298-491e-9a4b-9171412bbb6c
ca3ffe52-641a-4aa3-aed2-3b7ce5c35373

This is for plot types:  errorbar_plot and line_plot, but the problem probably exists for the other two types of plots, too:  bar_plot and scatter_plot.

The issue, or symptom, is the x_increment and y_increment.
1. when a value is entered for x_increment, this value is also entered (i.e., changed) for the y_increment.  **This is issue #1.**
2. after noticing this, I went to y_increment and changed it back to what I wanted.
3. so at this point, the input screen looked the way I wanted it. I am sure of it because an earlier job gave me ugly plots on the y-axis, so was careful to enter a value of 200 as the increment and checked before submission.  (Note the x_increment I specified as 2, so the y_increment would change to 2.)
4. Two plots are attached.  It is clear the y-axis looks bad.  It looks bad because even though I specified y_increment=200, with y-axis range of 0 to 1000 (the latter is good).   I believe the plotting code is using for the y_increment value the x_increment value, so that it is going from 0 to 1000 in increments of 2.
5. Then, when I take that job and do a "resubmit," the value entered for the y_increment, which should be a copy from the original and should be 200 (which is what I specified for the y_increment), shows up as a 2 (i.e., it shows up as the value specified for the x_increment.

So I do not know if the issue is in the web pages or a downstream entity.  But doubtful it is the plotting code, because that would not cause UI screen values to update other fields.

I do not know the priorities of things, but this seems a biggie, as I cannot generate plots for the tutorial.

![errorbar_plot0-t-4](https://user-images.githubusercontent.com/45767588/122552318-27bbd580-d004-11eb-88c7-762b9b1eea13.png)
![errorbar_plot0-t-6](https://user-images.githubusercontent.com/45767588/122552341-30141080-d004-11eb-8ec2-f9385323e3f6.png)
![line_plot0-t-4](https://user-images.githubusercontent.com/45767588/122552353-33a79780-d004-11eb-9e0f-a0092e8449ed.png)
![line_plot0-t-6](https://user-images.githubusercontent.com/45767588/122552362-386c4b80-d004-11eb-9c88-0e611237b65c.png)

**Comment by cckuhlman** [comment]
Sorry, I forgot.  For each plot, I am specifying the limit values:
set_x_limits=true
x_limit_lower=0
x_limit_higher=10
set_x_increment=true
x_increment =2

set_y_limits=true
y_limit_lower=0
y_limit_higher=1000
set_y_increment=true
y_increment =200 (which gets changed to 2).

But the issue needs to be checked for all of these boolean variables and all assignments of true and false.

**Comment by murli1201** [comment]
Hi Chris,

I just checked this and this was issue from our side. You were right. The y_increment was taking the value of x_increment. I have fixed it and merged to the master. Please have a look now.

Thank you.

**Comment by cckuhlman** [comment]
Thanks Murli.  We will rely on Master Machi to deploy.  chris
________________________________

**Comment by dmachi** [comment]
I have redeployed to alpha.  I haven’t tested anything yet.

**Comment by murli1201** [comment]
@cckuhlman can you verify if this issue is fixed?

**Comment by cckuhlman** [comment]
Yes, this is fixed.  Thanks.
________________________________
