### ISSUE TITLE
System seems to do "spelling correction" when entering file names

### ISSUE THREAD

**Issue by ssravi-1984** [NSSAC/CINES#212]
When running a job to get k-core distribution on a random graph that was generated in the system, I tried
to type in the output file name as "gnm-..." but the system does  spelling correction and changes "gnm" to "gym".
(I was able to see it and when I retyped the file name as "gnm-...", the system accepted it.)

   I don't know if this is an issue with my browser. It is, we may need to tell the attendees to temporarily disable
spelling correction. Thanks.

**Comment by dmachi** [comment]
This is a browser thing I believe.
