### ISSUE TITLE
On resubmission of completed "generate_graph_visualization" method, new methods generated are failed.

### ISSUE THREAD

**Issue by Rakesh-persistent** [NSSAC/CINES#213]
Hi Dustin,

For "generate_graph_visualization", we resubmitted few completed methods, but when we resubmit them, the methods are marked as failed. Below are the deatils

1. Completed job id **85a47fba-dffe-4064-8942-f5eb58a4e7fe** ( Failed job id - **4ca16ffc-1c3b-41e3-8b5f-1b800c21b663**) 
2. Completed job id **34168e7c-7de1-4aff-a66a-f61dd1fc7293** ( Failed job id - **7cce06a0-547c-422f-ab17-5381dc51185d**) 

Please let us know if you need any more information.

**Comment by dmachi** [comment]
I believe the completed jobs were run yesterday before the fixes to contract and clustering.  Yesterday contract/clustering was _always_ enabled even if you disabled it in the UI.  This was a bug.  This was fixed yesterday and I deployed it late last night.  So it is actually the original jobs that should have failed but didn’t.  In the newer jobs, you can see the error is reported in stderr:

ValueError: If scaling by community traits is requested (i.e. comm_degree or comm_size), then,contract must also be true.

I think that’s what you are seeing here.

Dustin

**Comment by dmachi** [comment]
Please confirm and if successful close this ticket.
