### ISSUE TITLE
Line up navigation bar menu items

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#214]
I switched some of the navigation menus to have sub-menus.  The style of the single item vs group item is slightly different and so things aren't lining up quite right.  I also notice the highlight shape of group items when hovering or selected is different than that of the single items. I suspect the latter is causing the former.

Single menu items:
<img width="547" alt="Net Science 2021-06-18 19-30-02" src="https://user-images.githubusercontent.com/190574/122623837-aa2bb000-d06b-11eb-951d-bfae55117ecf.png">

Group Items: 
<img width="316" alt="Net Science 2021-06-18 19-29-06" src="https://user-images.githubusercontent.com/190574/122623800-86686a00-d06b-11eb-9241-f469885285df.png">

Can you please take a look and see if you can get them to line up (including the UserMenu when logged in, and the Login/Register items when logged out).

**Comment by murli1201** [comment]
Hi Dustin, 
I have made a few changes in the Fuse libraries to fix this issue. I have also merged them to the master. Please verify.

**Comment by dmachi** [comment]
Fixed.
