### ISSUE TITLE
Sorting in the File Manager

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#215]
If it isn't too difficult, please enable sorting in the file manager table.  #214 is more important than this.  If you don't think you can finish that and also this today, we'll punt on this issue until after the release.

**Comment by murli1201** [comment]
Can you explain this sorting functionality in detail, please ?
Do you want files and folders to be sorted on load or need arrow buttons just as in My jobs? And for what all columns ?

**Comment by dmachi** [comment]
Yes, sorted just like on My Jobs.   We’re only viewing a single folder, so you should be able to just sort the array of files right before rendering.  I think all columns.   Again if this is going to be too difficult to get working today, we’ll wait.

**Comment by murli1201** [comment]
I just checked the code and it seems very difficult to get it working today. It will require some testing too. But, I will start working on it and try to complete it before the demo if possible.

**Comment by dmachi** [comment]
Ok, I’m not too worried about it.  If you do any work on this, best to do it in a branch just in case there are issues.

**Comment by murli1201** [comment]
I'm working on sorting in File manager. There are few minor issues that I'm trying to fix right now.
