### ISSUE TITLE
snap_GetSngVec1 Output Error

### ISSUE THREAD

**Issue by hcars** [NSSAC/CINES#222]
@dmachi I am seeing an issue with outputting the singular values here. Look at the job IDs: d12be3a0-490e-48c6-85a5-cb8cbb1f0079 and 86c632a0-ee86-438f-9b74-7435def3f222. Both failed after completing the singular value computations. They give the following error:

>   Error in instantiating output of PL type TFltVTFltV object of type RightSV.

**Comment by dmachi** [comment]
This never seemed to complete the calculations.  It looks like the snap method (or our wrapper code for that snap method) is failing here.   May need Chris to look at this one before Lucas fixes it.  I will disable this one for now. 

```
*********************
    Begin Primary 
*********************
   ==== echo inputs ====
  name of graph file containing graph to operate on.:  /input/inputFile_Graph
  graph type is Snap type, so one of:  PNGraph, PUNGraph, PNEANet.:  PUNGraph
  col index in graphName for the src (source) node of the edge (src, des).:  0
  col index in graphName for the des (destination) node of the edge (src, des).:  1
  The number of singular values/vectors to compute:  2
  output file name for variable SngValV:  /output/outputFile_SngValV.out
  output file name for variable LeftSV:  /output/outputFile_LeftSV.out
  output file name for variable RightSV:  /output/outputFile_RightSV.out
   ==== end echo ====
 
  Error in instantiating output of PL type TFltVTFltV object of type RightSV.
```

**Comment by dmachi** [comment]
Disabled for now in the UI.
