### ISSUE TITLE
Graph-plot rendering directed graphs when not contracted

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#226]
From Ravi:

It appears that in the plots where
the graph is not  contracted,  the edges appear as arrows.
When a contracted graph is shown, the edges are
undirected.

**Comment by hcars** [comment]
Yes, to do the contraction, we must the run community heuristics. This requires us to treat the graphs as un-directed; there is a UserWarning about this.

**Comment by hcars** [comment]
Ah, wait, all these graphs are PUNGraphs, so they should not be directed. Hmmm, let me show how igraph is deciding whether or not they are directed.

**Comment by hcars** [comment]
There is now a flag for directedness on the main branch of the plotting repo. However, running communities algorithms will still require converting to undirected.

**Comment by dmachi** [comment]
Ok, we’ll want to get the directionality from the graph type in the calling script and I don’t think I want to try that before the workshop today, so we’ll get back to this one afterwards.

**Comment by hcars** [comment]
Ok, thanks for the catch @ssravi-1984 .

**Comment by hcars** [comment]
We pushed a fix to this, and I just checked that the version alpha.net.science is running does not have this issue. Closing.

**Comment by dmachi** [comment]
I don't think this is actually fixed, because I don't see that anything is actually adding this dir flag to the calling script in the container image.

**Comment by hcars** [comment]
@dmachi, is the directed flag being collected by net.science currently? If not, then, I think we can safely pass the empty string for the directed argument for now. Also, when was the last build run? In the current https://github.com/NSSAC/graph-plot/blob/master/image/build.def#L33-L109, there is no directed flag passed which means that, if the build is from the current branch of the graph-plot repo., there should be no arrows on the graph outputs.

**Comment by dmachi** [comment]
I have updated both the image with the latest version of the code and of the wrapper script.  The wrapper script will now add  --directed  to the command line when the input file's autometa.edgeDirectionality == "directed"
