### ISSUE TITLE
sciduct--can codes be set up within sciduct to run periodically

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#23]
The use case for this would be to run web site scrapers to generate data (that can be used to make networks), periodically.  There are probably other such cases.  So this is a general sciduct question (versus running a task when specifically requested).

**Comment by dmachi** [comment]
There is no such capability right now, but one could certainly create a cron job that either:
a) submits a sciduct job that downloads and then pushes into sciduct 
b) downloads the networks (outside of sciduct) and then pushes them into sciduct.
