### ISSUE TITLE
API calls using node-sciduct package are not working on Firefox and Safari

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#239]
Hi Dustin,

The application is not working on Firefox and Safari as none of the API calls using node-sciduct package are not working. They are working fine on Chrome & Edge. The error reflecting on the console shows an issue regarding User Agent (which refers to the browser). 
I have attached the screenshot of one of the API errors produced on the console. Please have a look.

Note- All the APIs are producing the same error.

![BUG_2686_mac safari- create folder console error](https://user-images.githubusercontent.com/54397265/127318270-9dae3927-774f-4c87-a24c-a92bf9552906.png)

**Comment by dmachi** [comment]
I’ll take a look at this.  Is all of this code checked in to the "CSonNet_forms+-node-sciduct” branch so I can use it for testing?  Does this fail for all API calls or just these calls to the File Service?

**Comment by murli1201** [comment]
Yes, Dustin. All of this code is checked into the "CSonNet_forms+-node-sciduct” branch. It fails for all the API calls for file manager as well as jobs using node-sciduct package.

**Comment by dmachi** [comment]
I added user-agent to the access-control-allow-headers.  Can you please retest this and let me know if it is fixed?

**Comment by murli1201** [comment]
Thanks, Dustin. All the FS / JS APIs are now working in Firefox and Safari.
