### ISSUE TITLE
Node-sciduct package 'move' method not working

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#241]
Hi Dustin,

I tried using the 'move' method from the node-sciduct package with and without '/' at the end of the path as 2nd parameter ( destination path). But the method gives errors in both cases. The error is not related to parameters. I have added the screenshots of the params passed as well as the error that occurred. Please have a look.

![Screenshot (104)](https://user-images.githubusercontent.com/54397265/128184043-e2f3a820-0ecd-4910-a84f-ee48df05cf5c.png)
![Screenshot (107)](https://user-images.githubusercontent.com/54397265/128184052-70fec39a-fccf-4c15-bae0-d5149012ddc2.png)
![Screenshot (108)](https://user-images.githubusercontent.com/54397265/128184055-8454c244-eac5-4a60-a897-0c356485a4e6.png)

Thank you.

**Comment by dmachi** [comment]
I will take a look.

**Comment by murli1201** [comment]
Hi Dustin, any update on this issue?

**Comment by dmachi** [comment]
Not yet.  Out of town until tomorrow.  Hopefully I can work on this on Tuesday or Wed.

**Comment by murli1201** [comment]
Okay, Dustin. Thanks to inform.

**Comment by dmachi** [comment]
Please try this again.  There was a permissions checking error.  I think I have it fixed, please let me know if you still see errors.

**Comment by murli1201** [comment]
Thanks, Dustin. I am able to move items now without any issue!
