### ISSUE TITLE
File Sharing/Permissions

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#252]
We need an interface for modifying file permissions.  I would like to see some mockups about how you would see this working.

**Comment by murli1201** [comment]
Hi Dustin,
I am trying to test the APIs required for file permissions. The status is-

- For grant and revoke API-
  Request- grant(["/home/Manvitha/snap12",["read"],"dmachi",true])
  Response- **{id: 10, error: {code: 500, message: "'list' object has no attribute 'split'"}}**

I also tried replacing ['read'] with 'read', changing the path. but nothing changes. I am getting the same response for revoke.

- For queryUsers API-
  Request- queryUsers("eq(id,re:e*)") / queryUsers("eq(id,re:z*)") / queryUsers("eq(id,re:u*)")
  Response- Array[25]

**Irrespective of the request parameter, I am always getting an array of 25.**

**Comment by dmachi** [comment]
I mean we should match anywhere within the field (e.g., "dm") instead of just from the beginning of the string (e.g., "^dm"). So  the overall query should look like:

```or(eq(id,re:VAL),eq(first_name,re:VAL),eq(last_name,re:VAL))&limit(5)```

**Comment by murli1201** [comment]
Yes, we will do it this way. The API is working as expected.
