### ISSUE TITLE
Explain the expected output 

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#254]
In the description of a job definition, explain what the output will be (job output, file output and type).  This should show up on at least the job submission form, but probably also in the job definition list.

**Comment by murli1201** [comment]
Hi Dustin,
Is it okay if we show output data as shown in the below screenshot?

![Screenshot (130)](https://user-images.githubusercontent.com/54397265/134514414-b9a9a530-1624-487a-82d0-0a3f182e7373.png)

**Comment by dmachi** [comment]
I don’t think we should show “output file” like that, as that is really its internal name.  The name that will actually get used is what is shown by the user.  Instead, I think this should be done as an additional sentence at the end of the description.  It can be one of:

1.  For file output data only:
	“This task outputs a file of type <file type> in your chosen location”

2. For Job output only:
	This task outputs data attached to the job.  Click <here> to see the schema of the output.  
	For this one, you can make a popup show the output_schema in a popup.

3.  For both:
	This task outputs a file of type <file_type> in our chosen location and also generates output attached to the job.  Click <here> to see the schema of the job attached output.
	Similar to #2, clicking here can show a popup with the output_schema.

**Comment by murli1201** [comment]
Okay, I get it. I will make changes and then show you in the next meeting.
For job definition listing, do you want this to be in a similar way too?

**Comment by dmachi** [comment]
Yes, please.
