### ISSUE TITLE
cannot submit degree distro on Miami Wednesday graph

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#271]
<img width="1570" alt="Screen Shot 2021-12-11 at 7 50 12 AM" src="https://user-images.githubusercontent.com/45767588/145677119-b24f12c9-6011-4188-a16c-34c1ac448cc2.png">

Screen shot attached. I uploaded the file (into the resources area, not my own area).

When I hit the submit button, it gives me the red banner in the upper right corner stating "an internal error occurred.  Please try again."

Don't know if it's because I did not upload the graph to my own area.  I will try that now.

**Comment by cckuhlman** [comment]
It appears to be the case that the job would not run because I put the graph in the 'resources" area, because when I put that in my own area, I have then been able to do structural analyses of various kinds with no problems.

I wonder whether this suggests we should change permissions on the resources area to at least enable Ravi and me to upload graphs there.  No sense in loading very large networks to our own areas when they could be commonly used.

**Comment by dmachi** [comment]
You do have permissions to create files there, but it doesn’t look like your upload was successful. I’m not sure why.   What did you see when you tried to upload?  That is why the job failed to run something, but I’ll look into making sure that we show that error not give you the internal error message.

I will be out for the morning, but I will be back and working on this stuff this afternoon.

Dustin

**Comment by cckuhlman** [comment]
After I submitted, I stared at it a bit, but it was taking a while.  So I got up. When I returned, the upload screen was gone and there was no indication---that I saw, might have missed something---that something went wrong.  And the file was sitting in the directory, according to the web app, so I started submitting jobs on it.
