### ISSUE TITLE
ability to download plot right from plot screen

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#276]
A plot screen for a simulation output file plot is provided below.  This is with the new presentation system.

There is no download button on this screen.

<img width="1597" alt="Screen Shot 2021-12-11 at 2 15 07 PM" src="https://user-images.githubusercontent.com/45767588/145688830-d9c65a5d-3af4-4c23-8289-1c5d25064339.png">

**Comment by dmachi** [comment]
Closing this issue, which is now being tracked in #345
