### ISSUE TITLE
Revised landing page document

### ISSUE THREAD

**Issue by ssravi-1984** [NSSAC/CINES#3]
[landing_page_material_feb_20_2020.pdf](https://github.com/NSSAC/CINES/files/4232650/landing_page_material_feb_20_2020.pdf)

   We modified the landing page document.  In particular, we removed Persistent and New City from the list of  "Participating Institutions and Organizations". A new version of the landing page document is attached.

**Comment by Annapurna-Kupast** [comment]
@ssravi-1984 @dmachi 

The changes as per the updated document are done and committed to GitHub.
