### ISSUE TITLE
New version of material for the landing page

### ISSUE THREAD

**Issue by ssravi-1984** [NSSAC/CINES#32]
I have attached a pdf of the revised version of the landing page material for CINES.
In this version, I have included some publications that acknowledge support from the
NSF Grant for CINES. (I have a red comment to indicate the new part.)
 I have listed all the papers where I am a coauthor. It will be helpful if
Chris and Dustin can take a look and add any publications that I may have missed.
Thanks.

[may_11_landing_page_material.pdf](https://github.com/NSSAC/CINES/files/4610364/may_11_landing_page_material.pdf)

**Comment by cckuhlman** [comment]
Here are more work items for this issue.

--------------------------
Item 1:  Add the following four references to the **END** of section in the above pdf that has the heading "Publications Acknowledging Support from CINES NSF Grant OAC-1916805:"

Here are four more papers to put in the list of 

1.	Jiayu Li, Fugang Wang, Takuya Araki, Judy Qiu, “Generalized Sparse Matrix-Matrix Multiplication for Vector Engines and Graph Applications,” presented at the MCHPC’19: Workshop on Memory Centric High Performance Computing of SC'19 conference, Denver, Colorado.

2.	Langshi Chen, Jiayu Li, Cenk Sahinalp, Madhav Marathe, Anil Vullikanti, Andrey Nikolaev, Egor Smirnov, Ruslan Israfilov, and Judy Qiu, “SubGraph2Vec: Highly-Vectorized Tree-like Subgraph Counting,” presented at the 2019 IEEE International Conference on Big Data, Los Angeles, CA

3.	How Powerful Are Graph Neural Networks?. K. Xu, W. Hu, J. Leskovec, S. Jegelka. ICLR, 2019

4.	MASA: Motif-Aware State Assignment in Noisy Time Series Data. S. Jain, D. Hallac, R. Sosic, J. Leskovec, KDD Workshop on Mining and Learning from Time Series, KDD, 2019

----------------
Item 2 

Make all of these references have a uniform format, based on this particular reference:

A. Adiga, S. Krauss, O. Maksimov and S. S. Ravi, \Boolean Games: Inferring Agents Goals
Using Taxation Queries", to appear in Proc. 2020 International Joint Conference on Articial
Intelligence (IJCAI-2020).

Please look up these references and put page numbers on the entries, when the information exists.

-----------------
Item 3

Persistent, please identify who we are supposed to specify as the "Assignee" from Persistent for issues.

**Comment by Annapurna-Kupast** [comment]
@cckuhlman 

Please assign Git issues related to Persistent tasks to me (@Annapurna-Kupast) and Anju (@anju-thute)

**Comment by sachin-gawai-persistent** [comment]
@cckuhlman 
Here are the updates:
1. I have replaced the text mentioned in section 'Publications Acknowledging Support from CINES NSF Grant OAC-1916805' per the PDF and your comments (item 1)
2. Could you please elaborate on item 2 of your comments
3. In the PDF shared by Ravi, we also observed there are changes to section 'Links to Educational Materials on Network Science'. Do you want the contents in the PDF be updated on the UI? 

Upon your confirmation, I would do the remaining changes and commit the code to GitHub

**Comment by cckuhlman** [comment]
Responses to your comments.

1.  Great.  Thanks.
2. We want all references to be formatted the same.  The "template" reference example is this:

A. Adiga, S. Krauss, O. Maksimov, and S. S. Ravi, "Boolean Games: Inferring Agents Goals
Using Taxation Queries," Proc. 2020 International Joint Conference on Artificial Intelligence (IJCAI), 2020.

This format is:
a. author names first, in format first-initial-last-name, separated by commas.  Followed by a comma.
b. Then, the title of the article in double quotes.  Followed by a comma that is INSIDE the ending double-quote.
c.  Then, the name of the conference or journal.  Followed by a comma.
d.  Then, the page numbers (if they exist), in this format:   pp. 82--98.  Followed by a comma.
e.  Then, the year.  Followed by a period.

The above ref does not have page numbers.  Also, for the example, I have modified the actual reference to conform to these steps.

3.  Yes please.  We want all new material to be put in.

**Comment by sachin-gawai-persistent** [comment]
@cckuhlman

I have done the remaining changes and committed the code to GitHub

**Comment by cckuhlman** [comment]
Hey Guys:

Persistent has updated the static web pages.  Does Dustin deploy (in all of his spare time)?

@dmachi 
@ssravi-1984

**Comment by dmachi** [comment]
Yes, I will do the deployment.
