### ISSUE TITLE
not able to access directories in file service to specify a graph in the csonnet task when using ptest.net.science

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#333]
Am trying to do some tests under ptests with csonnet.  Am here:  https://ptest.net.science/apps/job-definition/development/CSonNet_Contagion_Simulation?version=3.1.3-1

When I click on the first input (input_file), to specify a graph file, I get the first screen capture below.  It is just spinning at "files" directory; will not allow drilling down.

But the files can be accessed from the file service; see the second attachment.

Note: as an aside, this problem does NOT occurr in net.science (i.e., without the ptest).

Thank you.

<img width="1652" alt="Screen Shot 2023-03-16 at 4 24 27 PM" src="https://user-images.githubusercontent.com/45767588/225768496-7c62e7b0-91e8-4428-9db0-d86031d53426.png">
<img width="1644" alt="Screen Shot 2023-03-16 at 4 24 50 PM" src="https://user-images.githubusercontent.com/45767588/225768533-30d0b7e4-09eb-4580-a58a-14fa4a412583.png">

**Comment by Vaibhav-Sontakke1** [comment]
When user clicks on SELECT FILE button and navigates to  Select File pop-up, user would be able to view the list of files.
Note – Earlier on Select File, the root folder was not loading.

**Comment by cckuhlman** [comment]
I'm sorry.  I'm not understanding again.
