### ISSUE TITLE
n.s web app--go over the sections (e.g., graphics) for the home page

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#38]
We need graphics and sexiness for the home page of the n.s web app.

There are ideas on the google doc here:  

https://drive.google.com/drive/folders/1IsALmpBRLb9ebv8mSxPqEkA4tlwB5qau

**Comment by dmachi** [comment]
This original intent of this ticket is subsumed by #45 and #73.    I'm copying the link to #79 as a new issue.
