### ISSUE TITLE
Another version of landing page (Date:  March 2, 2020)

### ISSUE THREAD

**Issue by ssravi-1984** [NSSAC/CINES#4]
I have added a new version of the material for the landing page. (See the attached file below.)
The changes in this version are as follows.

(a) The URL for Network Repository has been changed from "networkrepository.org"  to
"networkrepository.com".   (This correction was provided by Ryan Rossi after the Kickoff meeting for CINES on Feb. 28, 2020.)

(b) At the suggestion of one of the participants in the Kickoff meeting, the description of each link under the "Links to Educational Materials on Network Science" has been slightly reorganized. In particular, each link description specifies the name a person (or an orgranization), the person's affiliation and  location, name of the course (or book or topic) followed by the URL.

(c) A new link to the Network Science class taught by Natarajan Megahanathan at Jackson State University during Fall 2019 has been added.

Final note:  We are collecting the logos for the various partners. (Chris Kuhlman has set up a github repository for the logos. Each logo is either a png or a jpg file. If Persistent needs these in some specific format, please let us know.

   As usual, if you have any questions, please let me know. Thanks.

-- Ravi

[landing_page_material_mar_2_2020.pdf](https://github.com/NSSAC/CINES/files/4277767/landing_page_material_mar_2_2020.pdf)

**Comment by Annapurna-Kupast** [comment]
The suggested text changes are done and committed to GitHub.

@ssravi-1984 
For the logos, they are to be placed prior to the institution name and contacts in Collaborators menu. Is this understanding correct?
