### ISSUE TITLE
n.s web app--set up VM for the web app

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#43]
Dustin to work with Lady from rivanna whose name I cannot recall.  Michelle.

**Comment by dmachi** [comment]
This is done.

**Comment by dmachi** [comment]
Is there a reason you reopened this issue or was it an accident?

**Comment by cckuhlman** [comment]
Oh, now I get it.  I opened it, was looking for it, could not find it, saw it was closed and figured I fat fingered it ... not bothering to see that YOU closed it.  So, basically, the reason is stupidity.
