### ISSUE TITLE
n.s web app--put web pages for n.s web app (e.g., home/about) on VM

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#44]
Dustin to move pages up there for access.

**Comment by dmachi** [comment]
I will redeploy after the completion of #76, #77, #78.

**Comment by cckuhlman** [comment]
Also, issue #70 should also be fixed before redeploy if at all possible.

**Comment by dmachi** [comment]
When laying out the Home page.  Please use a style something like http://react-material.fusetheme.com/apps/academy/courses with a big header.  That header can say something like "Welcome to Net.Science".   You can use some of the content for the small print in that header style. The rest of the content and image referenced in the related issues should go below that.  Please use your best judgement to try to make it look nice.  We can refine further afterwards.

**Comment by dmachi** [comment]
Done
