### ISSUE TITLE
n.s web app--new (simplified) architecture figure for home page

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#45]
Simplified version of architecture.

**Comment by dmachi** [comment]
![image](https://user-images.githubusercontent.com/190574/81864619-e3295500-953a-11ea-8908-d60faaaecd49.png)

So here is a first idea/draft of a graphic.  Before I go through the process of finishing this, I'd like to get feedback on the concept from @cckuhlman and @ssravi-1984

**Comment by ssravi-1984** [comment]
The architecture diagram looks very appropriate and will be very useful in presentations. 

   One minor point is the following.  The system is expected to support the addition of software and networks by (authorized) users. Will be useful to indicate that explicitly in the architecture?

**Comment by cckuhlman** [comment]
What about considering for the bottom oval, other ovals "underneath" it to convey that other types of computational resources will also exist?  This is a common thing to do on graphics. I think this is to Ravi's question.

Also, maybe hang a block off of the "File Storage, ..." oval that says, "networks; biological and other data, learning materials".  That is a little wordy, but you get the idea.  This will call out the networks part of it, but granted, it messes up the style of the diagram.

The Gunrock app.  Is it too premature to put that in?  Are we certain that we are going to do it?

Looks good.  Thanks.

**Comment by dmachi** [comment]
I will add some more ovals with more detail and I'll remove gunrock, was just trying to be a little aspirational and show the _types_ of things, not an exhaustive list.

Is the general idea ok though?  This is what I would expect to use on our home page to represent the system to lay-ish people.

**Comment by ssravi-1984** [comment]
I think the general idea is pretty nice. The figure seems  very appropriate for
adding to the homepage. I am confident that it can be understood by people who
want to use net.science.

**Comment by cckuhlman** [comment]
yes, sorry.  the general idea is great.  thanks.  And we can leave Gunrock in if we think it is something like a certainty that we are going to do it.  Whatever you think best.

**Comment by dmachi** [comment]
![image](https://user-images.githubusercontent.com/190574/81958542-28ea2a00-95dc-11ea-9103-eb5d9f186680.png)

**Comment by cckuhlman** [comment]
Great.  I like it.  Thanks.

**Comment by dmachi** [comment]
![image](https://user-images.githubusercontent.com/190574/82370990-70f7bb00-99e7-11ea-90f1-b6e5492054e5.png)

Color Version

**Comment by dmachi** [comment]
I've committed a version of this figure into public/assets/images/cines/cines_overview.svg

**Comment by dmachi** [comment]
Closing this issue for now.  We can open or reopen to revise as needed.
