### ISSUE TITLE
A new version of the Landing Page document

### ISSUE THREAD

**Issue by ssravi-1984** [NSSAC/CINES#5]
[April_16_2020_landing_page_material.pdf](https://github.com/NSSAC/CINES/files/4489561/April_16_2020_landing_page_material.pdf)

I have attached a revised version of the document containing material for the landing page of the website for CINES.  To make it easier to see the new material that I have added, I have tagged all the new material using the word "(New)" in red.  If you need any clarifications, please feel free to contact me. Thanks.

**Comment by dmachi** [comment]
Done
