### ISSUE TITLE
Text Parsing Commit

### ISSUE THREAD

**Issue by anju-thute** [NSSAC/CINES#54]
@cckuhlman @Lucaslhm 

We have completed the text parsing for all SNAP methods. Now, we will proceed with – generating the Python source code for all these SNAP methods. 

For below listed SNAP methods, in order to generate IRs – we had to make some modifications to Text files.
Need confirmation from your side - if the changes made are correct or not.

Method Name | Required changes | Reference Link
-- | -- | --
DelZeroDegNodes | Removed the output parameter from function argument |  [link](http://snap.stanford.edu/snappy/doc/_sources/reference/DelZeroDegNodes.txt)
GetAnf | Parameter mismatch Napprox replace by NApprox | [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetAnf.txt)
GetBfsEffDiamAll | Parameter mismatch NTestNode replace by NTestNodes | [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetBfsEffDiamAll.txt)
GetEigVec | Parameter mismatch EigValV replace by EigVal | [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetEigVec1.txt)
GetInvParticipRat | Parameter mismatch EigVecs replace by MaxEigVecs | [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetInvParticipRat.txt)
GetLen2Path | Parameter *NId1* replace by *NId2* | [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetLen2Paths.txt)
GetNodesAtHop | Parameter *PGraph* replace by *Graph* | [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetNodesAtHop.txt) |
GetSngVec | Added ** in argument field | [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetSngVec1.txt) |
GenBaraHierar | Removed graph structure |  [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GenBaraHierar.txt)
GenCopyModel , GenGeoPrefAttach, GetNodeTriads   GetNodeInDegV, GetNodeOutDegV, GetSubTreeSz, GetTriadsAll | Remove space in file |  [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GenCopyModel.txt), [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GenGeoPrefAttach.txt), [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetNodeTriads1.txt), [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetNodeInDegV.txt), [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetNodeOutDegV.txt), [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetSubTreeSz.txt), [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetTriadsAll.txt)
IRs file not   generated for this below methods
GenRMatEpinions | There is no argument in function | [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GenRMatEpinions.txt)
GetTreeSig , GetTreeSig1 | Method not implemented yet |  [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetTreeSig.txt), [link](http://snap.stanford.edu/snappy/doc/_sources/reference/GetTreeSig1.txt)

Thanks,
Anju

**Comment by cckuhlman** [comment]
I looked at a few of these.  They appear to be ok.

Let us not do the GenRMatEpinions() method.  This appears to be a one-off method that is highly specific and is probably in there erroneously.

Let us go through at the meeting today the others that do not have links above.

Thanks.

**Comment by dmachi** [comment]
@cckuhlman anything else to do on this issue? Can it be closed?
