### ISSUE TITLE
networks--mark newman page of networks

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#57]
Get networks from here:  http://www-personal.umich.edu/~mejn/netdata/

**Comment by hcars** [comment]
@cckuhlman https://github.com/hcars/net.science_datasets now contains an edgelist, a mapping between node ids and their alias, and a master .csv with metadata on each network downloaded.

**Comment by hcars** [comment]
I think my script for grabbing the datasets from here is working well, and all the networks are currently checked into the repo.

**Comment by hcars** [comment]
I still need to scrape the networks from the following other live sites that Newman links to:

-  http://snap.stanford.edu/data/
- http://iv.slis.indiana.edu/db/index.html
- http://deim.urv.cat/~alexandre.arenas/data/welcome.htm
- http://vlado.fmf.uni-lj.si/pub/networks/data/UciNet/UciData.htm

**Comment by hcars** [comment]
I am closing this issue due to all networks linked to directly by Newman's site being scraped.
