### ISSUE TITLE
networks--pajek networks

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#61]
Get networks from here:  http://vlado.fmf.uni-lj.si/pub/networks/data/

**Comment by hcars** [comment]
I got all most of the data from these links. The networkx pajek parser didn't like the formatting on some of the pajek parsing. I'm not sure how much the leftovers are worth.

**Comment by cckuhlman** [comment]
Please show us on Tuesday.

**Comment by hcars** [comment]
It seems like the snap parsers dislikes the same files just as much as the networkx one. They may be malformed.

**Comment by hcars** [comment]
I was able to get all of these from Tim Davis's website.
