### ISSUE TITLE
networks--uri alon lab

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#62]
Get networks from here:  http://www.weizmann.ac.il/mcb/UriAlon/download/collection-complex-networks

**Comment by hcars** [comment]
I have gone through and scraped the networks that are linked to directly from the Uri Alon page.

**Comment by hcars** [comment]
> I have gone through and scraped the networks that are linked to directly from the Uri Alon page.
> The only two links that are still live that must be scraped are:
> B. subtilis transcription network - based on dbtbs.hgc.jp
> 
> C. elegans - neuronal synaptic circuitry network see: http://www.wormatlas.org/neuronsandcircuits.html

The C. Elegans link contains several variations on the C. elegans networks that is linked to Newman. I'm not sure how significant the difference is on this.

I wasn't able to find a network on the B. subtilis link. 

I'm not sure how to proceed on these two.

**Comment by cckuhlman** [comment]
ok, good for now.  please remember to bring up next week.  you can continue on with other sites if you have time.  thanks.

**Comment by hcars** [comment]
The networks linked to directly by this site have been scraped.
