### ISSUE TITLE
First commit of additional SNAP methods

### ISSUE THREAD

**Issue by anju-thute** [NSSAC/CINES#69]
@cckuhlman @Lucaslhm 
**Updates on Cines:**

- We have committed the Text Parser code in [Git](https://github.com/NSSAC/cines-parsing-snap.git) for all Primary SNAP methods as mentioned on the Git link - along with the infileXXX.inp, runXXX, runXXX.diff, outIrSnapMethodOnlyXXX.out.valid, outIrForDriverXXX.out.valid files.

We will also modify the [link](https://github.com/NSSAC/cines-snap-texts/blob/master/methods-to-implement/library-methods-to-implement.md#these-methods-are-helper-methds-used-within-main-methods-and-drivers-are-not-written-for-these) as per yesterday's discussion on call.

**Python Source Code Generation:**
o	We have generated python source code for 71 files till now. For 25 files we are getting an error while generating the Python source code and we are looking into these errors. 
We will share the details if we are not able to resolve these errors by Monday [before the call].
o	Please see the attachment for the list of SNAP methods – for which we are getting errors. 

Thanks,
Anju
[snapMethod.txt](https://github.com/NSSAC/CINES/files/4634998/snapMethod.txt)

**Comment by cckuhlman** [comment]
@anju-thute :  I do not see an attachment.  If it is here, can you tell me how to see it?

**Comment by anju-thute** [comment]
@cckuhlman 
I have added it. Previously something went wrong, so maybe attachment might be missed out.

**Comment by dmachi** [comment]
Looks like this conversation has moved over to #83.  Closing
