### ISSUE TITLE
n.s web app--the collaborators web page, reference to Network Repository

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#70]
We should have links to all groups, or none, it seems to me.

Right now, we have one link to the Network Repository.

Comments?

@dmachi 
@ssravi-1984

**Comment by ssravi-1984** [comment]
Good point. Since many institutions have multiple researchers and it will be messy to insert links for each of them, it is best to not have links for anyone.

**Comment by cckuhlman** [comment]
Persistent:  Please remove the link to the Network Repository on the "Collaborators" web page.
(This way, there are no links.)
See this page:
http://net.science/collaborators

(If at a later date, we decide to put in links, we'll do it for everyone.)
@dmachi 
@ssravi-1984

**Comment by cckuhlman** [comment]
@Annapurna-Kupast 
@dmachi 
Dustin will redeploy web pages when this issue and issues #76, #77, #78 are completed and closed.  (Just want to include this issue with Dustin's 76-78 issues.
Thanks.

**Comment by Annapurna-Kupast** [comment]
@cckuhlman @dmachi 
The changes to the contents are done by Sachin. However he would commit the changes along with the fix for Git #76

**Comment by sachin-gawai-persistent** [comment]
i have removed the link to the Network Repository on the "Collaborators" web page and committed the code

**Comment by dmachi** [comment]
Done
