### ISSUE TITLE
Fix link on the about page

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#78]
The sponsor link at the bottom of the about page is not clickable.

**Comment by Annapurna-Kupast** [comment]
@cckuhlman @dmachi 
Sachin has fixed the issue with the hyperlink for sponsor. However he would commit the changes along with the fix for Git #76

**Comment by sachin-gawai-persistent** [comment]
@cckuhlman @dmachi @Annapurna-Kupast  
I has fixed the issue with the hyperlink for sponsor and committed the code
