### ISSUE TITLE
Verify Snap Methods

### ISSUE THREAD

**Issue by anju-thute** [NSSAC/CINES#83]
@cckuhlman @Lucaslhm 

Hey Chris and Lucas,

I have committed all the driver code except for the method "GetClustCfAll".
Murali has executed the 75 snap method and he also committed the same in GitHub. He has verified 50 method output and he is not sure about 25 methods output. Could it be possible for you to verify the output? 
I am sharing the list of verified and non-verified snap methods.
[Cines-unverified.txt](https://github.com/NSSAC/CINES/files/4690772/Cines-unverified.txt)
[Cines-verified.txt](https://github.com/NSSAC/CINES/files/4690773/Cines-verified.txt)

Could you please check and let us know whether it is correct or not.

Thanks,
Anju

**Comment by dmachi** [comment]
@anju-thute Please use more descriptive tiles for tickets.  It is hard to keep track of Updates on CINES.  Thanks
