### ISSUE TITLE
GetAnf- Changes made in driver code to solve the error

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#86]
@cckuhlman @Lucaslhm

Hi Chris, Lucas,

For method "GetAnf", on generating the output files using the driver code, the output files were created but we were getting an error as "Error in writing output for variable -- DistNbrsV -- of method --snap.GetAnf(inputFile_Graph,graphType,srcCol,desCol,SrcNId,MxDist,IsDir,NApprox,outputFile_DistNbrsV) ---- to file."

As discussed in the meeting, I did the below changes according to the example in snap documentation, which resolved the error and correct output was generated-

(Original)
  for item in DistNbrsV:
fhout.write(str(item.GetVal1()) + "," + str(item.GetVal2()) + "," + str(DistNbrsV[item]) + "\n")

(Edited)
  for item in DistNbrsV:
fhout.write(str(item.Dat()) + "\n")

Note: As we have made changes to the driver code manually, it may give error if the driver code is regenerated in future.

Is there any other solution?

Thank you,
Murli

**Comment by cckuhlman** [comment]
@murli1201 

For this method, variable DistNbrsV is of type TIntFltKdV, per this page:  https://snap.stanford.edu/snappy/doc/reference/GetAnf.html?highlight=getanf.

Thus, one has to have this datatype in the datatype.dat file (in a directory under src).

And so there has to be an output template for this data type.  And that template should have this in it:

(Edited)
for item in DistNbrsV:
fhout.write(str(item.Dat()) + "\n")

and it should not have this in it:

(Original)
for item in DistNbrsV:
fhout.write(str(item.GetVal1()) + "," + str(item.GetVal2()) + "," + str(DistNbrsV[item]) + "\n")

chris

**Comment by murli1201** [comment]
Yes, i made the changes same as you said in the above comment today and everything worked correctly. I forgot to add comment actually.
Thanks.

**Comment by cckuhlman** [comment]
Can we close this issue?

**Comment by murli1201** [comment]
Yes, sure.
