### ISSUE TITLE
GetInvParticipRat- Changes made in driver code to solve the error

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#88]
@cckuhlman @Lucaslhm

Hi Chris, Lucas,

For method "GetInvParticipRat", on generating the output files using the driver code, the output files were created but we were getting an error as " Error in writing output for variable -- EigValIprV -- of method ---- snap.GetInvParticipRat(inputFile_Graph,graphType,srcCol,desCol,MaxEigVecs,TimeLimit,outputFile_EigValIprV) ---- to file.")

As discussed in the meeting, I did the below changes according to the example in snap documentation, which resolved the error and correct output was generated-

(Original)
 for item in EigValIprV:
 fhout.write(str(item.GetVal1()) + "," + str(item.GetVal2())  + "," + str(EigValIprV[item]) + "\n")

(Edited)
 for item in EigValIprV:
 fhout.write(str(item.GetVal1()) + "," + str(item.GetVal2()) + "\n")

Note: As we have made changes to the driver code manually, it may give error if the driver code is regenerated in future.

Is there any other solution?

Thank you,
Murli

**Comment by cckuhlman** [comment]
@murli1201 

This is exactly the same issue, in spirit, as issue 87 that we just responded to.

See  https://snap.stanford.edu/snappy/doc/reference/GetInvParticipRat.html?highlight=getinvparticiprat
This method:  GetInvParticipRat
This variable:  EigValIprV
The type:  TFltPrV

The output template name, in datatypes.dat file, for type TFltPrV, must contain the python statements that are the same as, or similar to, what you want:  

(Edited)
for item in EigValIprV:
fhout.write(str(item.GetVal1()) + "," + str(item.GetVal2()) + "\n")

Note, though, that the template should not have "EigValIprV" in the template file; rather, it should have a keyword.

chris

**Comment by murli1201** [comment]
Yes, i made the changes same as you said in the above comment today and everything worked correctly. I forgot to add comment actually.
Thanks.

**Comment by cckuhlman** [comment]
Can we close?
