### ISSUE TITLE
GetNodeTriadsAll- Changes made in input text file to resolve errors

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#89]
@cckuhlman @Lucaslhm

Hi Chris, Lucas,

For method "GetNodeTriadsAll", the input text file has two input parameters "ClosedTriads" and "OpenTriads" which are actually part of the Return value.

As discussed in the meeting, I deleted both the parameters, which resolved the error and correct output was generated.

Note- This issue does not need any assistance, it is added only for record purpose.

Thank you,
Murli

**Comment by cckuhlman** [comment]
So we can close this issue, yes?

**Comment by murli1201** [comment]
Yes, sure.
