### ISSUE TITLE
GetNodeEcc- Changes made in input text file to resolve errors

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#90]
@cckuhlman @Lucaslhm

Hi Chris, Lucas,

For method "GetNodeEcc", the input text file has an input parameter "Nid" which is an output parameter.

As discussed in the meeting, I changed the parameter from output to input, which resolved the error and correct output was generated.

Note- This issue does not need any assistance, it is added only for record purpose.

Thank you,
Murli

**Comment by cckuhlman** [comment]
@murli1201 

Thanks Murli.  So, when you are making these changes to the snap input text file, you are recording this in the summary file at https://github.com/NSSAC/cines-snap-texts/blob/master/methods-to-implement/library-methods-to-implement.md

This way, in the future, if another version of the snap library is released, and we have to do this again, we have a listing of all of the changes that we needed to make in the snap files.

**Comment by murli1201** [comment]
Yes, all the changes made to input files are recorded in the summary file.
