### ISSUE TITLE
GetESubGraph: Getting error while executing driver code

### ISSUE THREAD

**Issue by anju-thute** [NSSAC/CINES#99]
@cckuhlman @Lucaslhm

For snap method **GetESubGraph**, we are unable to execute driver code.
Please refer to the attachment which contains all the required input.
[GetESubGraph.zip](https://github.com/NSSAC/CINES/files/4711986/GetESubGraph.zip)

The folder **constructing driver**: have all the driver constructing file and driver code .py file.
The folder **parsing**: have all the inputs required to parse the snap method.
The third folder **GetESubGraph** is to execute the driver code.

Thanks,
Anju

**Comment by cckuhlman** [comment]
@anju-thute 

I think we are mixing together two different snap methods.

The issue has snap method name:  GetESubGraph.
The snap input text file is:  ConvertESubGraph
The IRs are for:  ConvertESubGraph
The driver main() method is for:  GetESubGraph

chris

**Comment by anju-thute** [comment]
Hi Chris,

Sorry for the mismatch in attaching the file. Now I have updated the .zip folder by replacing the existing one with new contains input.

Thanks,
Anju

**Comment by cckuhlman** [comment]
@anju-thute 

This is still inconsistent.  The driver code is different.

infilie77.inp:    GetESubGraph
outIrSnapMethodOnly77.out.valid:  GetESubGraph
inIrForDriver77.in.valid:  GetESubGraph
driver_auto_ConvertESubGraph_v01.py:  ConvertESubGraph

chris

**Comment by anju-thute** [comment]
Sorry for the inconsistency. Please refer to the updated folder.

[GetESubGraph.zip](https://github.com/NSSAC/CINES/files/4717678/GetESubGraph.zip)

**Comment by cckuhlman** [comment]
[all.run.stuff.GetESubgraph.tar.gz](https://github.com/NSSAC/CINES/files/4732800/all.run.stuff.GetESubgraph.tar.gz)


There is a fundamental problem/issue with Snap.  It is that this method uses an edge ID to do manipulations.  Snap has an edge ID that is an int.  Typically, an edge in a graph is specified by the two nodes that form that edge.  Hence, a directed edge from node 11 to node 23 is typically named (11,23).  The problem with the way Snap uses an int for an edge ID is:  what the edge ID is for an edge is not obvious.  It is not even known.  This creates a problem that we have to solve.

We will solve it by introducing a new data type.  The EIdV type is specified as TIntV.  We have a type TIntV, and it works, so we do not want to mess with that datatype.  We need to make a new type called TIntV_Subgraph.  This type will be used for this code, and for the code in issue #100.  Issue #100 code has the exact same problem.  For this datatype, the instantiation code template will be the same.  However, the template for the input template will be different than that for a normal TIntV.  Hence, we need the new type, TIntV_Subgraph.

The template needed is based on the code below:

'''
    ## ---------------------------------------
    ## Kuhlman
    ## This all here---until the next line of "## ---------------------------------------"
    ## has to be in the "input" template for EIdV variable.

    ## Read in edges of interest from file, as pairs of nodes.
    try:
        set_pairsNodes = set()
        fhin = open(inputFile_EIdV, "r")
        for aline in fhin:
            if len(aline.strip()) == 0:
               ## Empty line.
               continue
            if (aline.strip())[0] == "#":
                ## Line with comment.
                continue
            listTokens = aline.split()
            ## Two integers per line in file:  two integers form an edge.
            value01 = int(listTokens[0])
            value02 = int(listTokens[1])
            set_pairsNodes.add( (value01,value02)  )
        fhin.close()
    except:
        print("  Error in reading particular graph edges as pairs of nodes.")
        exit(1)

    ## Iterate through all edges in graph, getting the edge ID
    ## for each edge that was read in.
    print("  Number of graph nodes: ",Graph.GetNodes())
    print("  Number of graph edges: ",Graph.GetEdges())
    for EI in Graph.Edges():
        edgeId = EI.GetId()
        srcNode = EI.GetSrcNId()
        dstNode = EI.GetDstNId()
        myPair = (srcNode,dstNode)
        if (graphType == "PNEANet"):
            if (myPair in set_pairsNodes):
                ## This is edge of interest.
                EIdV.Add(EI.GetId())

    print("  number of particular edges read in: ",len(set_pairsNodes))
    print("  number of particular edge IDs: ",EIdV.Len())
    ## Kuhlman:  end of template for the "input template" for EIdV.
'''

The above code snippet is in the driver code in the attached tarball.

This is what this code does:
1. It reads in from file edges that are in the "normal" form:  two nodes determine an edge.  These are read into a set.
2.  Then, the code iterates over all edges in the input graph, and if the two nodes that form an edge in the input graph are also in the set of edges from step 1, then the edge ID is obtained for this edge, and it is added to EIdV, the vector of edge IDs.
3.  This EIdV is an argument into the snap method call.


The rest of the code is unaltered.
1.  The IRs are good as is.
2.  The CLAs in the driver code are good as is.

The driver code, attached in tarball, will run with the files in the tarball.  So, if you make the new templates, for the new data type, you should be able to reproduce this provided driver code.  And that driver code should run.

chris

**Comment by anju-thute** [comment]
Thanks, Chris!

We copied the provided .tar folder locally and tried to execute the driver, hence it is working correctly.
So we have committed the changes into the GitHub.

Thanks,
Anju
